### ISSUE TITLE
What's the release cadence?

### ISSUE THREAD

**Issue by Hades32** [cloudflare/workers-rs#108]
It has been two months since the last release and master contains fixes that I need. 

Is there a reason to not release patch versions after every merge?

**Comment by nilslice** [comment]
@Hades32 - we currently don't have a defined cadence, as this is still a beta / WIP project. However, we've recently added some new team members who will be working on this project much more regularly.

With that, expect to see more frequent releases, additional API support, and generally higher quality project management. 

We will be cutting a rather overdue release by end of next week - so keep an eye out!
