### ISSUE TITLE
no method named `kv` found for struct `worker::ScheduleContext`

### ISSUE THREAD

**Issue by katopz** [cloudflare/workers-rs#127]
```rust
#[event(scheduled)]
pub async fn foo(req: ScheduledEvent, env: Env, ctx: ScheduleContext) -> () {
    let kv_store = ctx.kv("BAR").unwrap();
}
```

![image](https://user-images.githubusercontent.com/97060/151704908-95d7fd69-790a-43f4-8280-3f6279cb3a63.png)

```
no method named `kv` found for struct `worker::ScheduleContext` in the current scope
method not found in `worker::ScheduleContext` rustc(E0599)
```

So how can I access kv when in scheduled event?

**Comment by Randoooom** [comment]
You have to access the kv using the given `env` (https://docs.rs/worker/latest/worker/struct.Env.html). The `ScheduleContext` only contains `wait_until` [(Cloudflare-Docs)](https://developers.cloudflare.com/workers/runtime-apis/scheduled-event#syntax-module-worker)

**Comment by katopz** [comment]
Oh, ok I mix it up with `ctx: RouteContext<()>` from other example, Thanks!
