### ISSUE TITLE
missing cargo lock file

### ISSUE THREAD

**Issue by happysalada** [cloudflare/workers-rs#135]
Hi, I'm trying to package this (worker-build actually) for a linux distribution (nixos). Would you mind committing the lockfile to the repo ? (without it, it's going to make reproducible builds harder).

**Comment by nilslice** [comment]
@happysalada - I've mentioned this in PR #138, if you don't mind taking a look. Thanks!

**Comment by happysalada** [comment]
all working good. One small comment though, the version for worker-build in the cargo.toml file is stuck at 0.0.5
if you don't mind updating when you have a moment.

**Comment by nilslice** [comment]
worker-build, like all crates in this repo, is versioned independently: https://crates.io/crates/worker-build

0.0.5 is the latest version published
