### ISSUE TITLE
ReferenceError: Window is not defined

### ISSUE THREAD

**Issue by katopz** [cloudflare/workers-rs#136]
## To reproduce
- use rust template https://github.com/cloudflare/rustwasm-worker-template
- add this code https://github.com/38/plotters/issues/332

## Fun facts
- It's working fine [without Cloudflare worker](https://github.com/38/plotters/blob/master/examples/stock.rs).
- When I comment out `Text` and everything working just fine via Cloudflare worker.
- I try to look at [text.rs](https://github.com/38/plotters/blob/master/src/style/text.rs) and didn't see anything related to `Window`.

I'm stuck here for a week (Rust noob) and not sure what causing this error.
Any hint is welcome. 🙏

**Comment by zebp** [comment]
This is caused by `window` not being defined in workers in general. It seems to be used [here](https://github.com/38/plotters/blob/master/src/style/font/web.rs#L32) in plotters along side some DOM api stuff. It seems that you won't be able to get this library to work in a worker.

**Comment by katopz** [comment]
> This is caused by `window` not being defined in workers in general. It seems to be used [here](https://github.com/38/plotters/blob/master/src/style/font/web.rs#L32) in plotters along side some DOM api stuff. It seems that you won't be able to get this library to work in a worker.

Thanks for head up, I think I can replace that fn with [no `window` version](https://github.com/38/plotters/blob/master/src/style/font/naive.rs#L30-L39)
```rust
    fn estimate_layout(&self, size: f64, text: &str) -> Result<LayoutBox, Self::ErrorType> {
        let em = size / 1.24 / 1.24;
        Ok((
            (0, -em.round() as i32),
            (
                (em * 0.7 * text.len() as f64).round() as i32,
                (em * 0.24).round() as i32,
            ),
        ))
    }
```

But now I get new error instead
```
 "description": "RuntimeError: unreachable\n    at wasm://wasm/002927d6:wasm-function[407]:0x49e55\n    at wasm://wasm/002927d6:wasm-function[915]:0x573ca\n    at wasm://wasm/002927d6:wasm-function[894]:0x57032\n    at wasm://wasm/002927d6:wasm-function[916]:0x573f3\n    at wasm://wasm/002927d6:wasm-function[450]:0x4c022\n    at wasm://wasm/002927d6:wasm-function[552]:0x4fedb\n    at wasm://wasm/002927d6:wasm-function[356]:0x46f12\n    at wasm://wasm/002927d6:wasm-function[433]:0x4b340\n    at wasm://wasm/002927d6:wasm-function[69]:0x182d1\n    at wasm://wasm/002927d6:wasm-function[189]:0x37948"
```
Do I should give up now? 😵

**Comment by katopz** [comment]
I think I know what other root cause, will get rid of all this and I'm good to go! https://github.com/38/plotters/blob/master/src/style/font/ttf.rs#L58
