### ISSUE TITLE
Feature request: `RequestInit` support for bulding requests with content type "application/octet-stream"

### ISSUE THREAD

**Issue by cjpatton** [cloudflare/workers-rs#140]
My use case requires a Worker to send a POST to an external server that expects the body to have a particular binary encoding. This doesn't seem possible with the current `Fetch` API. As far as I can tell, the body can only be constructed from a JSON object, like so:

```rust
let req_data: Vec<u8> = construct_req_data();

let req = Request::new_with_init(    
    "https://example.com/post_data",
    RequestInit::new().with_method(Method::Post).with_body(    
          Some(JsValue::from_str(&serde_json::to_string(&req_data))?)),
    ),    
)?;

let resp_data: Vec<u8> = Fetch::Request(req).send().await?.bytes().await?;
```

Here's the request that's produced:
```
POST /post_data HTTP/1.1
host: example.com
connection: keep-alive
accept-encoding: gzip, deflate
content-type: text/plain;charset=UTF-8
mf-loop: 1
content-length: 275

[242,133,190,60,175,148,143,207,195,107,125,50,24,28,20,219,149,197,95,4,245,90,45,178,238,67,156,88,121,38,78,31,0,0,0,0,97,152,30,96,0,0,0,0,97,152,58,128,0,0,156,94,141,18,191,39,28,67,72,89,222,73,232,198,37,167,126,229,237,191,55,125,174,19,100,96,25,73,152,161,235,185]
```

This won't work because example.com expects the content type to be "application/octet-stream" and the content to be raw bytes (instead of a JSON vector).

I'm a bit new to Workers (and workers-rs), so it's possible I'm missing something pretty fundamental.

Here's my ask. Can someone tell me if:

- Is what I'm describing possible with the [fetch() API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API)?
    - If "yes", is this use case supported by Workers?
        - If "yes", is this use case already supported by workers-rs?
            - If "yes", please point me to the API. An example would be ideal :)
            - If "no", is adding support for this use case feasible? I'd be happy to work on a PR, but I could use some guidance: Where would code changes be needed, are API-breaking changes permissible, etc.

**Comment by nilslice** [comment]
Without looking too closely at your use case, you should also be able to use the reqwest crate, possibly with a feature or two enabled to be fully compatible with wasm. 

I'll take a closer look at your specific request asap, but in case it can unblock you for the time-being, reqwest is worth a try.

**Comment by cjpatton** [comment]
Thanks for your help!
