### ISSUE TITLE
failed to get form data from request

### ISSUE THREAD

**Issue by happysalada** [cloudflare/workers-rs#146]
Hi, first of all, thank you for the amazing software! I'm really excited to start using cloudflare workers in rust!

I am testing a request with form data, and somehow, I am getting panics with "failed to get form data from request". I am trying to send a file.
Here is what I am trying to do on the frontend
```
    const dataArray = new FormData();
    files.accepted.forEach(file => dataArray.append("file", file));

    let res = await fetch("http://localhost:8787/audiowave", {
      method: "POST",
      headers: [["Content-Type", "multipart/form-data"]],
      body: dataArray
    })
```
I'm just using the fetch api from the browser with javascript. Am I missing something here ?
(the full frontend code so far can be found here https://github.com/happysalada/zik)

On the backend I'm doing
```
        .post_async("/audiowave", |mut req, _ctx| async move {
            match req.form_data().await?.get("file") {
```

and it seems that the panic is at the form_data() part. Full backend code can be found https://github.com/happysalada/audiowave_rs

(I'm taking care of cors btw, but it seems I should add a cors header in the error response as well. Would the best way to do that be something like
```
                let cors = Cors::default()
                    .with_max_age(86400)
                    .with_origins(vec!["*"])
                    .with_methods(vec![
                        Method::Get,
                        Method::Head,
                        Method::Post,
                        Method::Options,
                    ]);
         Response::error("message", 500)
               .with_cors(&cors);
```
(I'm not sure the "*" works for all origins)

**Comment by zebp** [comment]
After looking into this I believe this is actually a problem with your JavaScript. You are manually specifying the `content-type` header without a boundary eg: `multipart/form-data;boundary="boundary"`. Usually the fetch API will insert the `content-type` header if you give a `FormData` as the body, so removing the `content-type` header should do the trick.

**Comment by happysalada** [comment]
and of course you were right! Thank you for the tip and the quick response!
