### ISSUE TITLE
Unable to update durable object with webhook events.

### ISSUE THREAD

**Issue by cdmurph32** [cloudflare/workers-rs#149]
It doesn't seem possible to modify a durable object from a received websocket event. This is really an issue with wasm and async which force wasm_bindgen_futures::spawn_local() to require static lifetimes. https://github.com/rustwasm/wasm-bindgen/issues/1733#issuecomment-552021431

Perhaps these are just the limitations of the system, but I'm filing this bug for two reasons.
1. I am far from a Rust expert, so I am hopefully missing something. 
2. There may be some way to work around this in worker-rs. 

This is an example of the problem. Let's say I had a durable object for collaborative image editing and the image was a field of the durable object.
```
  #[durable_object]
  pub struct Editor {
      image: Option<String>,
      image_id: String,
      state: State,
      env: Env,
      sessions: Vec<WebSocket>,
  }
```
It is fairly simple to send events to the clients when self.image is updated by REST calls through the router.
```
for server in &self.sessions {
     server.send_with_str(img).expect("could not relay text");
}
```
However it does not seem possible to listen for events and update the image accordingly. Durable objects can't be given static lifetimes and the router doesn't handle websockets directly.

```
fn handle_session(&self, server: WebSocket) {
       wasm_bindgen_futures::spawn_local(async move {
              let mut event_stream = server.events().expect("could not open stream");
              while let Some(event) = event_stream.next().await {
                  match event.expect("received error in websocket") {
                      WebsocketEvent::Message(msg) => {
                          if let Some(text) = msg.text() {
                              self.img = Some(text);
                          }
                      }
                      WebsocketEvent::Close(_) => console_log!("Websocket Closed"),
                  }
              }
          })
      }
```
Since I am trying to assign a value to a field to the durable object which lives on the stack, this gives the following error. The same would be true if I tried to use KV or storage, since those are also part of the durable object Env field.
```
error[E0759]: `self` has an anonymous lifetime `'_` but it needs to satisfy a `'static` lifetime requirement
```

**Comment by zebp** [comment]
It is possible, it's just that Rust's lifetime guarantees make it so we have to put in some extra work. [Here](https://github.com/zebp/ws-relay) is an example repo of me using references counting via an [Arc](https://doc.rust-lang.org/stable/std/sync/struct.Arc.html) and interior mutability through a [Mutex](https://docs.rs/futures/latest/futures/lock/struct.Mutex.html) to accomplish something similar.

[This](https://www.youtube.com/watch?v=8O0Nt9qY_vo) video by [Jon Gjengset](https://github.com/jonhoo) should do a good job explaining why you'd need reference counting and interior mutability in Rust.
