### ISSUE TITLE
Support outbound HTTP calls

### ISSUE THREAD

**Issue by fkautz** [cloudflare/workers-rs#150]
It appears that workers supports outbound HTTP calls, but I cannot find a path to do this easily in rust workers. I can see the bindings generated in sys-worker, but don't see how to reach or use them. Perhaps it is already supported and I just don't understand how to use it? If not, please consider this as a feature request.

**Comment by zebp** [comment]
This is currently possible, you can use either [Fetch](https://docs.rs/worker/latest/worker/enum.Fetch.html) or a third party library with wasm support, like [reqwest](https://docs.rs/reqwest). For a code example there's one in `worker-sandbox` [here](https://github.com/cloudflare/workers-rs/blob/main/worker-sandbox/src/lib.rs#L316)

**Comment by seeekr** [comment]
Thanks for the pointer, @zebp, but for new users it's really a big deal: There is simply no example at all, neither in the README, nor in the Rust docs, that shows that simple single line of code: How to do the equivalent of a `fetch()` call?

It'd be great to have that both in the README and in the top-level Rust doc. If you don't disagree I might send a PR when I get around to it.

(For future folks searching for this until it's in the docs:

```rust
let req = Request::new("https://example.com", Method::Post)?;
// fetch() with a request
Fetch::Request(req).send().await?;
// fetch() with just a url
Fetch::Url("https://example.com".parse()?).send().await?;
```

**Comment by seeekr** [comment]
Perhaps an API question in addition: I'd have expected a send() method on a Request. Wouldn't that be the most natural way of doing it? And also adding one on Url, for consistency, and because it's basically the same idea as the current API?
