### ISSUE TITLE
I tried omitting (await) in durable objects, but it doesn't seem to work.

### ISSUE THREAD

**Issue by piloer** [cloudflare/workers-rs#151]
I saw an explanation of durable objects lifespan here
https://developers.cloudflare.com/workers/runtime-apis/durable-objects/#durable-object-lifespan

When I try to omit ctx.wait_until and remove .await from the Fetch, the durable objects does not wait for the request to complete

**Comment by SeokminHong** [comment]
`async` bodies and other futures are lazy: they do nothing until they are run. (https://rust-lang.github.io/async-book/03_async_await/01_chapter.html)

You can use `worker::Context::wait_until` function that makes the execution context can live after the response is returned.
