### ISSUE TITLE
Setting a timeout using Fetch in Rust

### ISSUE THREAD

**Issue by PirosB3** [cloudflare/workers-rs#159]
Hi 👋 - I'm using CloudFlare workers to make external HTTP requests to other sites. I want to set a timeout on my `fetch` request to limit my client's upper bound latency. Does anyone have some boilerplate code or advice to implement something similar to [this](https://community.cloudflare.com/t/timeout-with-fetch/25249/5)? or - is there a way to set a timeout on `fetch`?

Thanks!

**Comment by zebp** [comment]
This is currently possible with [worker-sys](https://docs.rs/workers-sys) using the [Fetch](https://docs.rs/worker-sys/latest/worker_sys/global/struct.WorkerGlobalScope.html#method.fetch_with_request_and_init) api with an [AbortSignal](https://docs.rs/web-sys/latest/web_sys/struct.AbortSignal.html) passed to the [RequestInit](https://docs.rs/web-sys/0.3.56/web_sys/struct.RequestInit.html#method.signal) using a timeout via `setTimeout`.

This currently would take quite a bit of interaction with the `worker-sys` crate and it seems like this should be an actual feature of the fetch api bindings.  I'll put an actual rust-y way to do this on my todo list :)

**Comment by PirosB3** [comment]
Thank you so much! for now, the client is doing a timeout on their side, but it would be nice for our CF workers to provide a reasonable fallback 😃
