### ISSUE TITLE
workers::Request doesn't implement wasm_bindgen

### ISSUE THREAD

**Issue by cholcombe973** [cloudflare/workers-rs#162]
I have a javascript function that takes in a request object to pull out headers. The JS makes function calls like: `request.headers.get('Content-Type')`. 
I'd like to pass the `workers::Request` struct to it with wasm_bindgen but bindgen errors out saying:
```
the trait `wasm_bindgen::convert::IntoWasmAbi` is not implemented for `worker::Request`
```
Is there a work around for this? I'm new to the wasm ecosystem so this is kinda confusing for me.

**Comment by quangIO** [comment]
You should use worker_sys::Request instead of worker::Request as the former is the actual JS object.
