### ISSUE TITLE
Question:  Response::from_bytes -> change "application/octet-stream" to "image/jpg"

### ISSUE THREAD

**Issue by remotejob** [cloudflare/workers-rs#163]
I try to show image from KV content -> "image: JPEG image data, Exif standard: [TIFF image data..."

let (value, _metadata) = kv.get("27B6QvlGpyJ8dy9T1k3TZiGSZ4j").bytes_with_metadata::<Vec<usize>>().await?;
let imgbytes = value.unwrap_or_default();
Response::from_bytes(imgbytes)

I  think I must change "application/octet-stream" to "image/jpg"

**.with_headers(headers)** don't work for me.

**Comment by zebp** [comment]
Currently this is possible if you use mutate the headers after the fact, for example this respond with the correct content type:
```rust
use worker::*;

const IMAGE_BYTES: &[u8] = include_bytes!("./example.jpg");

#[event(fetch)]
pub async fn main(req: Request, env: Env, _ctx: worker::Context) -> Result<Response> {
    Router::new()
        .get("/", |_, _| {
            let image_bytes = IMAGE_BYTES.to_vec();
            let mut response = Response::from_bytes(image_bytes)?;

            let headers = response.headers_mut();
            headers.set("Content-Type", "image/jpg")?;
            
            Ok(response)
        })
        .run(req, env)
        .await
}
```
