### ISSUE TITLE
Method for easily getting query parameters

### ISSUE THREAD

**Issue by zebp** [cloudflare/workers-rs#179]
Currently getting query parameters is a something similar to the code below:

```rust
let mut example = None;
for (k, v) in req.url()?.query_pairs() {
    if k != "task_id" {
        example = Some(v.as_ref());
    }
}
```

A `param` method on [Url](https://docs.rs/worker/latest/worker/struct.Url.html) would be a nice QOL improvement.

**Comment by sengho66** [comment]
If you are still keen, have a look at this crate I recently worked on!
https://github.com/sengho66/worker-route/tree/main
