### ISSUE TITLE
[Feature] Is it safe to send `Env`?

### ISSUE THREAD

**Issue by cjpatton** [cloudflare/workers-rs#194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The `Env` struct doesn't implement `Send` due to a `*mut u8` field.

```rust
use async_trait::async_trait; // 0.1.53
use std::{marker::PhantomData, sync::{Arc, Mutex}};
use worker::*; // latest on main

#[async_trait]
trait SayHello {
    async fn say_hello(&self);
}

// This is my data type.
struct Person<D>(Arc<Mutex<RouteContext<D>>>);

#[async_trait]
impl<D: Send> SayHello for Person<D> {
    async fn say_hello(&self) {}
}
```

This doesn't compile:
```
   |
27 |     async fn say_hello(&self) {}
   |                               ^^ future created by async block is not `Send`
   |
   = help: within `RouteContext<D>`, the trait `Send` is not implemented for `*mut u8`
note: captured value is not `Send` because `&` references cannot be sent unless their referent is `Sync`
  --> src/main.rs:27:25
   |
27 |     async fn say_hello(&self) {}
   |                         ^^^^ has type `&Person<D>` which is not `Send`, because `Person<D>` is not `Sync`
   = note: required for the cast to the object type `dyn Future<Output = ()> + Send`
```

[I've found I can get this to compile](https://users.rust-lang.org/t/solved-how-to-move-non-send-between-threads-or-an-alternative/19928/4) using unsafe code. First, wrap `RouteContext<D>` and implement `Send` for it:

```rust
struct Wrapper<D>(RouteContext<D>);
unsafe impl<D> Send for Wrapper<D> {}
```

Next, change my type to
```rust
struct Person<D>(Arc<Mutex<Wrapper<D>>>);
```

From what I've read, putting the data behind a mutex makes this code safe. (In fact, the code won't compile without the mutex.)

An alternative to wrapping this code would be to (unsafely!) implement `Send` for `Env`. Here is a Playground illustrating this solution: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=5649e591f318b1c10b52cf51d1793a41

Is there any reason to think this would be unsafe to do?

**Comment by dbw9580** [comment]
You can use `#[async_trait(?Send)]` to remove the `Send` bound on your future type. Workers' request handlers do not require `Send` futures, e.g. [get_async](https://docs.rs/worker/latest/worker/struct.Router.html#method.get_async), so you will not have trouble using your type in the request handlers.

**Comment by cjpatton** [comment]
That worked for me! Thanks @dbw9580.

**Comment by v1olen** [comment]
> You can use `#[async_trait(?Send)]` to remove the `Send` bound on your future type. Workers' request handlers do not require `Send` futures, e.g. [get_async](https://docs.rs/worker/latest/worker/struct.Router.html#method.get_async), so you will not have trouble using your type in the request handlers.

I think it's worth it to include this info in the readme
