### ISSUE TITLE
Lacking pre-built binaries on RaspberryPi 

### ISSUE THREAD

**Issue by bcpeinhardt** [cloudflare/workers-rs#200]
Hello!
I'm trying to use a raspberry pi 4 running ubuntu server as a dev environment. I'm running into issues with missing pre-built binaries. Currently, I'm stuck at 
```
ubuntu@ubuntu:~/development/project_name$ npx wrangler dev
 ⛅️ wrangler 2.0.8 
-------------------
Running custom build: cargo install -q worker-build && worker-build --release
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
    Finished release [optimized] target(s) in 0.26s
[INFO]: Installing wasm-bindgen...
Error: no prebuilt wasm-opt binaries are available for this platform: Unrecognized target!
To disable `wasm-opt`, add `wasm-opt = false` to your package metadata in your `Cargo.toml`.
Error: wasm-pack exited with status exit status: 1

✘ [ERROR] Command failed with exit code 1: cargo install -q worker-build && worker-build --release
```
If possible I'd like to somehow configure this to build from source or point it to a binary on my machine. Any suggestions would be appreciated.

**Comment by bcpeinhardt** [comment]
Update: Working on a https://github.com/rustwasm/wasm-pack/issues/913 based solution

**Comment by zebp** [comment]
wasm-pack has this same issue on the new arm MacBooks, but you can get around it by specifying a path to a wasm-opt you get yourself via the `WASM_OPT` environment variable. That's what I've been doing for a while.

Closing because this is isn't workers-rs specific.
