### ISSUE TITLE
[BUG] Error: %1 is not a valid Win32 application. (os error 193)

### ISSUE THREAD

**Issue by gagan-suie** [cloudflare/workers-rs#222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of `workers-rs` are you using?

0.0.11

### Describe the bug

When calling `wrangler dev` I get the following error:

```
Error: %1 is not a valid Win32 application. (os error 193)
X [ERROR] Command failed with exit code 1: cargo install -q worker-build && worker-build --release 
```

### Steps To Reproduce

Windows 10
Visual Studio 2022 Community
Build Tools 2022
Wrangler 2.0.28
Workers 0.0.11

Reproducible in this repository:
https://github.com/CodeCrowCorp/infinibuild-api

**Comment by zebp** [comment]
I've identified the issue and have a plan to fix it soon, but in the mean time having `esbuild` on your path should do as a workaround.

**Comment by kpietraszko** [comment]
That workaround didn't work for me 🤔

**Comment by TTTPOB** [comment]
no, having `esbuild` in my path won't fix `%1 is not a valid Win32 application` for me.

**Comment by zebp** [comment]
Re-opening until the next release for visibility

**Comment by ByteAlex** [comment]
Workaround to use the "fixed" build - edit your build-command to the following:
`cargo install -q --git https://github.com/cloudflare/workers-rs && worker-build --release`

**Comment by zebp** [comment]
Closing this, `worker-build v0.0.8` has just released. Update your `build.command` to
```toml
[build]
command = "cargo install -q worker-build --version 0.0.8 && worker-build --release"
```

**Comment by TTTPOB** [comment]
![image](https://user-images.githubusercontent.com/19909103/202358230-fcd88c31-8497-47c6-8ea3-9de1f8c6cd86.png)
am I missing something?
(the Chinese sentence means `[Error: %1 is not a valid Win32 application. (os error 193)])`)
