### ISSUE TITLE
🐛 BUG:  worker-build: command not found

### ISSUE THREAD

**Issue by gustavotr** [cloudflare/workers-rs#242]
### What version of `Wrangler` are you using?

2.1.13

### What operating system are you using?

Linux

### Describe the Bug

Running `npm run dev` or `wrangler dev` on the `worker-rust` template fails with the message:
```bash
/bin/sh: linha 1: worker-build: command not found
Command failed with exit code 127: cargo install -q worker-build --version 0.0.7 && worker-build --release
```

**Comment by zebp** [comment]
If you run `echo $PATH` do you see your `/home/user/.cargo/bin` or `/Users/user/.cargo/bin`? I'm assuming that it's installing `worker-build` but it can't execute it as it isn't on your path.

**Comment by gustavotr** [comment]
Yeah, It wasn't there. Manually adding to the path also did not work so I copied the binary that was inside the build folder into my `/usr/bin` folder and that solved the issue.
