### ISSUE TITLE
🐛 BUG: failed to publish Rust worker

### ISSUE THREAD

**Issue by sbihel** [cloudflare/workers-rs#245]
### What version of `Wrangler` are you using?

2.4.2

### What operating system are you using?

Mac

### Describe the Bug

Within the last 24 hours, publishing a Rust/WASM worker stopped working, with the following error from the API:

```
Uncaught TypeError: WebAssembly.Instance(): Import cloudflare/wrangler2#9 module="env" error: module is not an object
  or function
    at shim.js:13:9
   [code: 10021]
```

So far I have tried with `workers-rs` `0.0.11` and `0.0.12`; `worker-build` `0.0.7` and `0.0.8`; and `wrangler` `2.2.3`, `2.3.2`, and `2.4.2`.

**Comment by JacobMGEvans** [comment]
Did this happened after you changed some code in their worker?

**Comment by sbihel** [comment]
No, but I think I understand the issue. This error would typically occur at runtime (well known issue with `ring` in this case) but now it is checked statically. So if I'm correct the issue is purely on my side and I have to make sure the problematic code isn't included when it's unused.

**Comment by JacobMGEvans** [comment]
> No, but I think I understand the issue. This error would typically occur at runtime (well known issue with `ring` in this case) but now it is checked statically. So if I'm correct the issue is purely on my side and I have to make sure the problematic code isn't included when it's unused.

If this resolves your issue, please mention it here and close the issue 😄

**Comment by sbihel** [comment]
Confirmed, apologies for the false positive
