### ISSUE TITLE
Reorganize before an official release

### ISSUE THREAD

**Issue by ObsidianMinor** [cloudflare/workers-rs#25]
The naming of the crates in this project are a bit everywhere. It'd be nice to consolidate the names of everything and reorganize before committing to any crates.io releases.

As it stands there are currently five crates each with wildly different names:
* edgeworker-sys
* worker-rs-macros
* libworker
* worker
* rust-worker-build

libworker could be dropped in favor of just defining everything in worker instead of using worker to re-export everything. Currently libworker is separate so it can be imported by worker-rs-macros however the macros crate never uses it so it's an unnecessary dependency. With the base name "worker", we can easily turn this into four separate easily identifiable crates.

* worker-sys - For low-level FFI bindings
* worker-macros - For macros
* worker - For bringing everything together with convenience types
* worker-build - As a build command

On top of this, it may be favorable to drop the rust-sandbox crate. Instead of testing or experimenting in a sandbox, things normally written in the sandbox would be better if written as an [example](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#examples) in the worker crate. Then things written as examples for testing during development can be referenced later by users.

**Comment by nilslice** [comment]
This is a good call, and thanks for suggesting names that are available on crates.io. Definitely needs some cleanup here now that the dust has settled a bit. I'll try to fit it in today and re-publish the crates under their new names.

> On top of this, it may be favorable to drop the rust-sandbox crate. Instead of testing or experimenting in a sandbox, things normally written in the sandbox would be better if written as an example in the worker crate. Then things written as examples for testing during development can be referenced later by users.

This is all true, except I plan to add automated integration tests that will publish `rust-sandbox` and run curl commands against it. I don't blame you for suggesting we axe the crate though.. it looks like a bunch of nonsense :) I plan on cleaning it up to be more useful against integration test HTTP calls. 

Creating proper examples is probably a good idea too, but idk if they can actually be run with cargo since the Worker needs to be executed by preview or edge worker runtime. Will put some more thought into this.

**Comment by jyn514** [comment]
> Creating proper examples is probably a good idea too, but idk if they can actually be run with cargo since the Worker needs to be executed by preview or edge worker runtime. 

This is an awful hack, but you could run `wrangler dev` from within the example and just have a standalone rust file next to it.

**Comment by ObsidianMinor** [comment]
Maybe could add a lightweight testing framework around it like a Miniflare of sorts specifically for examples.

**Comment by nilslice** [comment]
> This is an awful hack, but you could run wrangler dev from within the example and just have a standalone rust file next to it.

You tried this? `wrangler dev` delegates to the build command, so we'd need a `wrangler.toml` somewhere, and it would expect to be able to use the custom build which relies on a bunch of preconditions to be true. I'd be surprised if this works, but pleasantly so :)

**Comment by nilslice** [comment]
> Maybe could add a lightweight testing framework around it like a Miniflare of sorts specifically for examples.

We could try something like that, but a soft-goal here is to not require users to have any JS tooling installed to use this. Or at least to prove it is possible.

**Comment by nilslice** [comment]
This is now completed!
