### ISSUE TITLE
Custom status code support

### ISSUE THREAD

**Issue by jakeswenson** [cloudflare/workers-rs#28]
I'd like to be able to set arbitrary status codes (201, 202, 204, 302, etc.) and currently, that is impossible because `Response::status_code` is private and there is no method to create a custom response or modify a response like `with_status(self, code: u16)` (similar to `with_headers`.)

This will go away with #13.

**Comment by nilslice** [comment]
Totally agree @jakeswenson. Upgrade to `worker` v0.0.4 and you'll have this new method available. 

https://github.com/cloudflare/workers-rs/blob/2427771d0ae54bd9fa47fc6195fc959d3e849e7c/worker-sandbox/src/lib.rs#L334-L335
