### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'fetch')

### ISSUE THREAD

**Issue by mikeumus** [cloudflare/workers-rs#282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of `workers-rs` are you using?

0.0.12

### Describe the bug

Running `npx wrangler dev` produces:

``` javascript
12:55:06 PM GET /favicon.ico 500
✘ [ERROR] Uncaught TypeError: Cannot read properties of undefined (reading 'fetch')

  const ret = wasm.fetch(addHeapObject(req), addHeapObject(env), addHeapObject(ctx));
                   ^
      at fetch
  (/Users/michaelmooring/Documents/Mikeumus/code/callOpenAI/build/worker/shim.mjs:181:19)
```

### Steps To Reproduce

1. `npm init cloudflare project_name worker-rust`
1. `cd project_name`
1. `npx wrangler dev`

**Comment by paulgb** [comment]
I started getting the same today too. It seems to also happen on workers 0.0.11. I think it was probably another dependency update that caused it, and am trying to narrow down which one.

**Comment by perry-birch** [comment]
I've been running into this for awhile using 0.0.12.
Falling back to 0.0.9 works but introduces other dependency chain conflict issues with other libs I'm trying to integrate...

**Comment by KianNH** [comment]
Update to the `0.0.13` version of the `worker` crate to fix this

**Comment by paulgb** [comment]
Unfortunately, updating to 0.0.13 doesn't work for me. I have tried, on both Mac and Linux:

- run `npm init cloudflare project_name worker-rust`
- run `npm run dev`
- access the local URL printed out
- observe error mentioned above
- update to workers `0.0.13` in `Cargo.toml`
- run `npm run dev`
- observe error mentioned above

**Comment by novacrazy** [comment]
I was able to fix this just now by upgrading `worker-build`

```toml
[build]
command = "cargo install -q worker-build && worker-build --release"
```

**Comment by a1ecbr0wn** [comment]
Doesn’t work for me, same issue

**Comment by anton-kasperovich** [comment]
Experienced the same, after changing version of the crate and wrangler worker-build version to 0.0.9 as suggested - it works, both locally and once deployed. Thanks!
```
# Cargo.toml
[dependencies]
cfg-if = "0.1.2"
worker = "0.0.14"
serde_json = "1.0.67"
```

```
# wrangler.toml
[build]
command = "cargo install -q worker-build --version 0.0.9 && worker-build --release"
```
