### ISSUE TITLE
WebSocket server support

### ISSUE THREAD

**Issue by nihaals** [cloudflare/workers-rs#30]
- [Workers JS reference](https://developers.cloudflare.com/workers/runtime-apis/websockets)
- [Workers JS guide](https://developers.cloudflare.com/workers/learning/using-websockets)

It probably makes sense for WebSocket clients (to remote servers) to use the same type as what's returned from the `new WebSocketPair()` equivalent (although probably only relevant if it's added at the same time as server support).

**Comment by nilslice** [comment]
Thanks, @nihaals! WebSocket support is definitely on the roadmap. If you have thoughts on a nice Rust interface for it, please don't hesitate to share!

**Comment by zebp** [comment]
Seems like this was implemented in #124. If there is still behavior you think is missing feel free to ask for the issue to be re-opened.
