### ISSUE TITLE
🐛 BUG: build wasm filenames not as expected

### ISSUE THREAD

**Issue by 0x65-e** [cloudflare/workers-rs#310]
### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version of `Wrangler` are you using?

2.13.0

### What operating system are you using?

Windows, WSL and Linux

### Describe the Bug

After not running wrangler for a couple months, I tried to deploy and encountered the following error:

```shell
> npx wrangler publish --dry-run
 ⛅️ wrangler 2.13.0 
--------------------
Running custom build: cargo install -q worker-build && worker-build --release
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
    Finished release [optimized] target(s) in 0.36s
[INFO]: Installing wasm-bindgen...
[INFO]: Optimizing wasm binaries with `wasm-opt`...
[INFO]: Optional fields missing from Cargo.toml: 'description', 'repository', and 'license'. These are not necessary, but recommended
[INFO]: :-) Done in 1.65s
[INFO]: :-) Your wasm pkg is ready to publish at C:\Users\mcrai\Documents\Git Repos\mattcraig.tech\build.
X [ERROR] Could not resolve "./index_bg.wasm"

    index_bg.js:1:22:
      1 │ import * as wasm from './index_bg.wasm';
        ╵                       ~~~~~~~~~~~~~~~~~

1 error
Error: esbuild exited with status exit code: 1

X [ERROR] Command failed with exit code 1: cargo install -q worker-build && worker-build --release
```

Looking at the build directory, it appears that `index.wasm` is being generated but no `index_bg.wasm`, which is causing esbuild to fail.

I have not made any changes to my code or build configuration, just tried re-running workflows that worked 2 months ago with an updated version of wrangler.

**Comment by ChurchillSD** [comment]
I had this issue, and got around it by updating "worker" in my cargo.toml to the latest version:

worker = "0.0.16"

I previously had 0.0.9 (I think)

**Comment by eli-front** [comment]
any updates here?

**Comment by eli-front** [comment]
Here's a workaround for those looking. Change your `wrangler.toml` to specify the build version
```
[build]
command = "cargo install -q worker-build --version ^0.0.8 && worker-build --release" # required
```

**Comment by katopz** [comment]
same here

```
macOS 13.4
wrangler 3.1.0
wasm-pack 0.10.3
```

`npx wrangler dev` also have this issue, Thanks for workaround btw.

**Comment by mimoo** [comment]
cross posted here: https://github.com/cloudflare/rustwasm-worker-template/issues/41

**Comment by okletsgo** [comment]
same here

> Here's a workaround for those looking. Change your `wrangler.toml` to specify a build version before `0.0.9`
> 
> ```
> [build]
> command = "cargo install -q worker-build --version ^0.0.8 && worker-build --release" # required
> ```

thank you!

**Comment by dev-ardi** [comment]
Same under linux. I feel like cloudflare workers are abandoned

**Comment by cruzluna** [comment]
> Here's a workaround for those looking. Change your `wrangler.toml` to specify a build version before `0.0.9`
> 
> ```
> [build]
> command = "cargo install -q worker-build --version ^0.0.8 && worker-build --release" # required
> ```

Yep fixed my issue. 

Here is my fixed `wrangler.toml`:
```toml
name = "name"
workers_dev = true
compatibility_date = "2022-01-20"
main = "build/worker/shim.mjs"


[[rules]]
globs = [ "**/*.wasm" ]
type = "CompiledWasm"

[build]
command = "cargo install -q worker-build --version ^0.0.8 && worker-build --release" # required

```

**Comment by Kakapio** [comment]
@kflansburg I believe you should be able to close this now? It looks to me as if this issue no longer exists with the latest version of workers.

**Comment by sanghng** [comment]
> ### Điều này liên quan đến (các) sản phẩm Cloudflare nào?
> Người chiến tranh
> 
> ### What version of `Wrangler` are you using?
> 2.13.0
> 
> ### Bạn đang sử dụng hệ điều hành nào?
> Windows, WSL và Linux
> 
> ### Mô tả lỗi
> Sau khi không chạy wrangler trong vài tháng, tôi đã cố gắng triển khai và gặp phải lỗi sau:
> 
> ```shell
> > npx wrangler publish --dry-run
>  ⛅️ wrangler 2.13.0 
> --------------------
> Running custom build: cargo install -q worker-build && worker-build --release
> [INFO]: Checking for the Wasm target...
> [INFO]: Compiling to Wasm...
>     Finished release [optimized] target(s) in 0.36s
> [INFO]: Installing wasm-bindgen...
> [INFO]: Optimizing wasm binaries with `wasm-opt`...
> [INFO]: Optional fields missing from Cargo.toml: 'description', 'repository', and 'license'. These are not necessary, but recommended
> [INFO]: :-) Done in 1.65s
> [INFO]: :-) Your wasm pkg is ready to publish at C:\Users\mcrai\Documents\Git Repos\mattcraig.tech\build.
> X [ERROR] Could not resolve "./index_bg.wasm"
> 
>     index_bg.js:1:22:
>       1 │ import * as wasm from './index_bg.wasm';
>         ╵                       ~~~~~~~~~~~~~~~~~
> 
> 1 error
> Error: esbuild exited with status exit code: 1
> 
> X [ERROR] Command failed with exit code 1: cargo install -q worker-build && worker-build --release
> ```
> 
> Looking at the build directory, it appears that `index.wasm` is being generated but no `index_bg.wasm`, which is causing esbuild to fail.
> 
> Tôi đã không thực hiện bất kỳ thay đổi nào đối với mã hoặc cấu hình xây dựng của mình, chỉ thử chạy lại quy trình làm việc đã hoạt động cách đây 2 tháng với phiên bản cập nhật của wrangler.
