### ISSUE TITLE
Unable to call into_async_read on worker::ByteStream

### ISSUE THREAD

**Issue by monken** [cloudflare/workers-rs#312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'd like to call `into_async_read` from futures_util::stream::try_stream::TryStreamExt on the worker::ByteStream. Unfortunately, that fails because the worker::ByteStream uses its own Error class which is not compatible.

Would it be possible to use `std::io::Error` instead?

**Comment by zebp** [comment]
Sadly it's not possible, because workers-rs is a wrapper around the JS runtime APIs we have to account for any JS-based errors that might get thrown.

**Comment by monken** [comment]
OK so I created my own shim, please let me know if this a dumb idea or not:

```rust
#[pin_project]
struct StandardStream<'a> {
    #[pin]
    inner: worker::ByteStream,
}

impl <'a> StandardStream<'a> {
    fn new(stream: worker::ByteStream) -> Self {
        Self { inner: stream }
    }
}

impl Stream for StandardStream<'_> {
    type Item = Result<Vec<u8>>;

    fn poll_next(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        let this = self.project();
        match futures_util::ready!(this.inner.poll_next(cx)) {
            Some(Ok(chunk)) => {
                Poll::Ready(Some(Ok(chunk)))
            }
            Some(Err(err)) => {
                Poll::Ready(Some(Err(std::io::Error::new(std::io::ErrorKind::Other, err.to_string()))))
            },
            None => Poll::Ready(None),
        }
    }
}
```

**Comment by monken** [comment]
@zebp your insight would be highly appreciated. I'm a Rust newbie so please don't hold back :)
