### ISSUE TITLE
[BUG] Missing port in Request.url

### ISSUE THREAD

**Issue by jancespivo** [cloudflare/workers-rs#329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of `workers-rs` are you using?

0.0.16

### Describe the bug

On localhost `req.url().unwrap().port()` returns always `None` instead of ie. 8787.

**Comment by KianNH** [comment]
The URL in a remote development Worker isn't the `localhost:8787` that you access it on locally, that `localhost:8787` is just the proxy that Wrangler runs locally to connect you to the remote preview on the edge.

Remote development is the default in Wrangler 2, if you use local development (`--(experimental)-local` in Wrangler 2 or default in Wrangler 3) then it would have a URL of `http://127.0.0.1:8787/`.
