### ISSUE TITLE
[BUG] Enabling "d1" feature will cause a build error

### ISSUE THREAD

**Issue by penzur** [cloudflare/workers-rs#344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of `workers-rs` are you using?

0.0.17

### What version of `wrangler` are you using?

3.0.1

### Describe the bug

Hi,

I'm getting a `the package testproject depends on worker, with features: d1 but worker does not have these features.` error when I enable `d1` feature in `Cargo.toml`. I am currently using wrangler 3.x, but I've also tried it on 2.x and I get the same error.

### Steps To Reproduce

1. Set `worker = { version = "0.0.17", features = ["d1"] }` in your `Cargo.toml`
2. Run `npx wrangler dev` or  `wrangler dev` if you have it installed locally.

**Comment by penzur** [comment]
I got it working now. Will close this one.

**Comment by spicyzboss** [comment]
> I got it working now. Will close this one.

Can you share how to get it works? I'm now facing with this issue.

**Comment by rdbisme** [comment]
> > I got it working now. Will close this one.
> 
> Can you share how to get it works? I'm now facing with this issue.

Update the version from 0.0.15 (as in the example) to latest release. Then do a `cargo update`.
