### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by nuvanti** [cloudflare/workers-rs#35]
How do I access Cloudflare cache?

**Comment by nilslice** [comment]
Hi @nuvanti, are you referring to this Cache API? 
https://developers.cloudflare.com/workers/runtime-apis/cache

If so, we have not implemented the binding or utility layer yet. But I will make sure it is prioritized on the roadmap!

**Comment by nuvanti** [comment]
Yes, that's what I am referring to. Thanks.

**Comment by nilslice** [comment]
@nuvanti , I have created #37 Cache API implementation discussion and would love to continue this thread over there. Will close for now and if you have feedback or suggestions or would like to consider picking up the implementation in a PR please add comments to the discussion thread. Thanks!
