### ISSUE TITLE
Confusing 403 error with `wrangler dev`

### ISSUE THREAD

**Issue by binarybana** [cloudflare/workers-rs#36]
I had `wrangler login`ed to my Cloudflare account already, but when trying to `wrangler dev` I received a 403 error that was not very useful in helping me determine the cause:
```
wrangler dev
🌀  Running cargo install -q worker-build && worker-build --release
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
    Finished release [optimized] target(s) in 0.03s
[INFO]: Installing wasm-bindgen...
[INFO]: Optimizing wasm binaries with `wasm-opt`...
[INFO]: Optional fields missing from Cargo.toml: 'description', 'repository', and 'license'. These are not necessary, but recommended
[INFO]: :-) Done in 2.10s
[INFO]: :-) Your wasm pkg is ready to publish at /home/jason/src/my-project/build.
Error: HTTP status client error (403 Forbidden) for url (https://api.cloudflare.com/client/v4/accounts/ae126deafb76cf635e5e028f594434ac/workers/subdomain/edge-preview)
```
I think I tracked it down to not enabling the free cloudworker component in my account, but 1) I wasn't expecting a local `dev` cli command to require that and 2) it would have been good to spell that out in the returned 403.

Now it seems to be working past that (but getting a different error I'm trying to make sense of). Thanks for the cool project!

**Comment by nilslice** [comment]
Ah, thanks for pointing that out. I haven't encountered that one before. 

Yea, `dev` is actually a local proxy to your worker running on the edge - it definitely isn't obvious and you're not alone in thinking it's fully local. 

Feel free to share any detail about the new error you're facing and we can try to help. 

Glad you're into this project!

**Comment by binarybana** [comment]
Thanks @nilslice! 

Here's the other error I received, which in the spirit of 'try one more time' actually went away and started working after waiting for a minute or two and retrying.
```
wrangler dev
🌀  Running cargo install -q worker-build && worker-build --release
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
    Finished release [optimized] target(s) in 0.03s
[INFO]: Installing wasm-bindgen...
[INFO]: Optimizing wasm binaries with `wasm-opt`...
[INFO]: Optional fields missing from Cargo.toml: 'description', 'repository', and 'license'. These are not necessary, but recommended
[INFO]: :-) Done in 2.10s
[INFO]: :-) Your wasm pkg is ready to publish at /home/jason/src/my-project/build.
Error: error sending request for url (https://300671de1512409d9ab9bb78a60030c4.binarybana.workers.dev/cdn-cgi/workers/preview/?s0=AZukn7Mgmv-Osvb_YyScJ9u1xzj6ZCLpLSX0kV7RExxJ6dzxvJy6UpFph_CjC57Ox1qEOCa8SPwaNP1wna7AT_6feYwq0z1aURRximCUK1RRy4YbGl23e3JY_V-48JcxiN2-vNzGF7MvcYmqAT9XnRWKCfC8QEijITpAYnhLc2KgYP-YADbH5rLu29JE_Xo7wfLXKozSypnuuvl4HN7yMd4G-RyWOyyhFs-sbyPY-AVPhxBxwkrq2JW2OnqwrhfOwHg5yBXPFjkEjOS_0K38UWFKSd6nHWilgr_doEICxK9uNX5yc0naA8q1etdw-iQebrIYehVbaqKIKes8qqRxycEOC0GkRpGDWcE-9lOmCIMHit1nqUgh4JL-Cml8rSuu7Q): error trying to connect: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1543:SSL alert number 40

Caused by:
    0: error trying to connect: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1543:SSL alert number 40
    1: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1543:SSL alert number 40
    2: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1543:SSL alert number 40
```

**Comment by nilslice** [comment]
Interesting! ok I'll do a little investigating tomorrow / early next week - but it sounds like it's working alright now? 

Also, if this happens again, would you mind filing an issue on the https://github.com/cloudflare/wrangler repo?

**Comment by binarybana** [comment]
Will do! And yes it is working now.

**Comment by InnovativeInventor** [comment]
I can confirm that this issue still exists -- I encountered the exact same set of errors that @binarybana is reporting. I didn't enable the free Cloudflare worker component in my account as well and stumbled upon this GitHub issue.

After enabling Cloudflare workers, `wrangler dev` gave me the same SSL handshake failure message:
```
[INFO]: :-) Done in 4.56s
[INFO]: :-) Your wasm pkg is ready to publish at [redacted].
Error: error sending request for url (https://[redacted]): error trying to connect: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1543:SSL alert number 40

Caused by:
    0: error trying to connect: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1543:SSL alert number 40
    1: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1543:SSL alert number 40
    2: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1543:SSL alert number 40
```
~20-30 minutes later, the problem resolved itself.

**Comment by anonshail** [comment]
This issue seems to still exist. Facing the exact same issue. Once I enabled the free component, the error changed to the second one. I am just hoping that 20 - 30 mins later, it starts working as it did for the other users.

> Thanks @nilslice!
> 
> Here's the other error I received, which in the spirit of 'try one more time' actually went away and started working after waiting for a minute or two and retrying.
> 
> ```
> wrangler dev
> 🌀  Running cargo install -q worker-build && worker-build --release
> [INFO]: Checking for the Wasm target...
> [INFO]: Compiling to Wasm...
>     Finished release [optimized] target(s) in 0.03s
> [INFO]: Installing wasm-bindgen...
> [INFO]: Optimizing wasm binaries with `wasm-opt`...
> [INFO]: Optional fields missing from Cargo.toml: 'description', 'repository', and 'license'. These are not necessary, but recommended
> [INFO]: :-) Done in 2.10s
> [INFO]: :-) Your wasm pkg is ready to publish at /home/jason/src/my-project/build.
> Error: error sending request for url (https://300671de1512409d9ab9bb78a60030c4.binarybana.workers.dev/cdn-cgi/workers/preview/?s0=AZukn7Mgmv-Osvb_YyScJ9u1xzj6ZCLpLSX0kV7RExxJ6dzxvJy6UpFph_CjC57Ox1qEOCa8SPwaNP1wna7AT_6feYwq0z1aURRximCUK1RRy4YbGl23e3JY_V-48JcxiN2-vNzGF7MvcYmqAT9XnRWKCfC8QEijITpAYnhLc2KgYP-YADbH5rLu29JE_Xo7wfLXKozSypnuuvl4HN7yMd4G-RyWOyyhFs-sbyPY-AVPhxBxwkrq2JW2OnqwrhfOwHg5yBXPFjkEjOS_0K38UWFKSd6nHWilgr_doEICxK9uNX5yc0naA8q1etdw-iQebrIYehVbaqKIKes8qqRxycEOC0GkRpGDWcE-9lOmCIMHit1nqUgh4JL-Cml8rSuu7Q): error trying to connect: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1543:SSL alert number 40
> 
> Caused by:
>     0: error trying to connect: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1543:SSL alert number 40
>     1: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1543:SSL alert number 40
>     2: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1543:SSL alert number 40
> ```
