### ISSUE TITLE
[BUG] WebSockets are broken [regression]

### ISSUE THREAD

**Issue by paulgb** [cloudflare/workers-rs#360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of `workers-rs` are you using?

0.0.17

### What version of `wrangler` are you using?

3.3.0

### Describe the bug

When returning a `Response::from_websocket`, workerd complains with:

```
panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(RangeError: Responses may only be constructed with status codes in the range 200 to 599, inclusive.
RangeError: Responses may only be constructed with status codes in the range 200 to 599, inclusive.
```

This appears to be a regression between `workers-rs` 0.0.13 and 0.0.14.

### Steps To Reproduce

I have created a repro repo [here](https://github.com/paulgb/cloudflare-repro).

1. `git clone https://github.com/paulgb/cloudflare-repro.git`
2. `npm i`
3. `npm run dev`
4. In Chrome, navigate to `about:blank`
5. Open the JavaScript console and run `new WebSocket("ws://127.0.0.1:8787/")`
6. Observe that a failure is reported in the console, and that an error is printed in the terminal

To verify that this is a regression, modify `Cargo.toml` and change the version of `worker` to `0.0.13` and `worker-sys` to `=0.0.7`, then repeat the steps.

**Comment by TonyGiorgio** [comment]
Yeah, websocket connections have been severely broken since `0.014` and there's been radio silence on it: https://github.com/cloudflare/workers-rs/issues/299

It's really prohibiting me upgrading on some projects and for ones that I need to use `D1` or `TCP`, I just can't do `wss`.
