### ISSUE TITLE
[Feature] being able to use fs to write/read file to disk

### ISSUE THREAD

**Issue by mimoo** [cloudflare/workers-rs#365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm getting "operation not supported on this platform" when I try to write to disk, is there a simple way to solve this?

**Comment by kflansburg** [comment]
Workers does not make a filesystem available. We have discussed supporting an ephemeral filesystem through the WASI API, but this is not in the current roadmap.
