### ISSUE TITLE
[Feature] Hibernatable WebSockets API

### ISSUE THREAD

**Issue by iridiumsoft** [cloudflare/workers-rs#376]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

I recently tried Hibernatable WebSockets API on worker with typescript and it's really cool. But this API is not available in workers-rs. is anyone working on it right now? Can it be added to 0.0.19?

**Comment by j-white** [comment]
+1 for Hibernatable WebSockets API in Rust

**Comment by DylanRJohnston** [comment]
Hey guys, I've got a working [PR](https://github.com/cloudflare/workers-rs/pull/434) for most of the APIs required for Hibernatable Web Sockets. It wasn't as hard as I thought it would be after reading through the `wasm-bindgen` [documentation](https://rustwasm.github.io/wasm-bindgen/)

**Comment by kflansburg** [comment]
Completed in #436
