### ISSUE TITLE
Consider making Router Data not an Option

### ISSUE THREAD

**Issue by tv42** [cloudflare/workers-rs#38]
It seems the only reason `Router` and `RouteContext` `data` method return an `Option<Data>` is because you've decided to implement `Default` for a router. Nothing seems to use that default. Could I convince you to remove the `Default` and make data be not optional? That would remove a `.unwrap()` from practically every handler of every app using data.

For inspiration/justification/examples:

- https://docs.rs/tide/0.16.0/tide/struct.Request.html#method.state
- https://github.com/http-rs/tide/blob/1d6f120c9e6c0e723bb8929dc0f601cd4f9d1449/src/server.rs#L59-L61

**Comment by nilslice** [comment]
Yes, that's most likely a leftover artifact from an earlier design... I will definitely take another look at this and reconsider. Unless there is another reason that currently escapes me, I agree it should not use `Option`.

The other thing I dislike about the Router but could not figure out a way around is the requirement to pass _some_ data, even just unit type `()`, to satisfy the generic type parameter. Haven't had time to revisit that, but if you're digging around in that part of the code and happen to have an idea, I'm all ears!

**Comment by tv42** [comment]
See Tide's `::with_state(x)` vs `::new()` for a way to hide the `()` from the caller who doesn't care. It'll still show up in types, of course.

https://github.com/http-rs/tide/blob/1d6f120c9e6c0e723bb8929dc0f601cd4f9d1449/src/server.rs#L59-L61

**Comment by nilslice** [comment]
@tv42 - of course, seems so obvious in hindsight :) Thanks for pointing that out. 

The only downside is that we still need to add `Clone` to the bounds on `D` for the data. I am still trying to get some notion of a "global" for the router to be created in the global scope, which would likely require this anyways. (Worker's Isolates can share global state if they are in the same colo and under other conditions)

I've got a branch up with this change if you would like to take a look: https://github.com/cloudflare/workers-rs/commit/f95b3ada228c5bd6d52c56910af73860e166dcdb

**Comment by nilslice** [comment]
This has been updated in #50 - thanks for the feedback @tv42 !

**Comment by nilslice** [comment]
> The only downside is that we still need to add Clone to the bounds on D for the data.

For posterity, `Clone` was _not_ added as a bound to `D` here. Instead, a `&D` is returned from `ctx.data()` and if you need ownership, you can implement `Clone` on your types via derive or manually.
