### ISSUE TITLE
[Feature] add support for crypto.DigestStream

### ISSUE THREAD

**Issue by carlsverre** [cloudflare/workers-rs#383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

According to the docs, workers have access to a non-standard Crypto type called "DigestStream". It would be nice if this crate provided ergonomic access to this class as well as a nice way to compute the digest while doing something else with a request stream.

**Comment by dakom** [comment]
I took a stab at it in https://github.com/cloudflare/workers-rs/pull/529
