### ISSUE TITLE
[Feature] Implement message-level `ack` and `retry` methods

### ISSUE THREAD

**Issue by PatrickLaflamme** [cloudflare/workers-rs#385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://blog.cloudflare.com/messages-at-your-speed-with-concurrency-and-explicit-acknowledgement/

In May 2023, the js worker library added `ack` and `retry` functionality at the message level. This hasn't yet been added to the worker-rs library. Are there any plans to do so?

**Comment by kflansburg** [comment]
Addressed in https://github.com/cloudflare/workers-rs/pull/335
