### ISSUE TITLE
[BUG] d1 does not appear to support bools

### ISSUE THREAD

**Issue by JorgeAtPaladin** [cloudflare/workers-rs#387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of `workers-rs` are you using?

0.0.18

### What version of `wrangler` are you using?

3.8.0

### Describe the bug

`Error: Error: invalid type: floating point `0`, expected a boolean - Cause: Error: invalid type: floating point `0`, expected a boolean`

```rs
struct UserData {
    pub id: String,
    pub is_admin: Option<bool>,
}

let d1 = ctx.env.d1("dashboard")?;
let q = d1.prepare("SELECT * FROM user WHERE id = ?1 LIMIT 1")
    .bind(&[subject.into()])?;
let result: Option<UserData> = q.first(None).await?;
match result {
    Some(thing) => Response::from_json(&thing),
    None => Response::error("Not found", 404),
}
```

It should be noted that using a normal `bool` instead of an `Option` doesn't work either and gives the same error.

### Steps To Reproduce

Try parsing a SELECT query into a struct with boolean fields, after inserting an element with boolean fields.

**Comment by lewsmith** [comment]
Same issue, did you ever find a solution?

**Comment by kflansburg** [comment]
In https://github.com/cloudflare/workers-rs/releases/tag/v0.0.22 we introduced an improved D1 API, which should include support for bools, have you tried since then?

**Comment by lewsmith** [comment]
> In https://github.com/cloudflare/workers-rs/releases/tag/v0.0.22 we introduced an improved D1 API, which should include support for bools, have you tried since then?

I'm on v0.1.0. 

After further investigation it was due to some JsValue conversion code. I sorted it by using a custom serde deserializer on the prop causing the error that converts from a float to a boolean.

**Comment by lewsmith** [comment]
> > After further investigation it was due to some JsValue conversion code. I sorted it by using a custom serde deserializer on the prop causing the error that converts from a float to a boolean.
> 
> Was the bug in `workers-rs`?

In my case @kflansburg (using a custom D1 API), no. The issue was with my own float to bool code. 

I am however switching to the worker-rs D1 API soon so will confirm if it's working okay using that also.
