### ISSUE TITLE
Don't have a default request server

### ISSUE THREAD

**Issue by dev-ardi** [cloudflare/workers-rs#394]
The technology behind this is great. I really like having serverless webassembly but I don't agree with the decision of having a web server in the same crate for several reasons:

Workers server is a bit feature incomplete and it can't compete with other libraries such as Axum, Actix and Rocket. If you really want to use the current server you should add another crate.

Ideally the request and response given from workers should be easy to port to other libraries.

This crate feels like it doesn't have that many resources assigned to it from cloudflare and most seem to go to the server. In my opinion this crate should do one thing and do it well: Integrate the workers ecosystem with the rest of the rust ecosystem. This would speed up developement.

The modularity would also allow for easier contributions.

**Comment by BrandonDyer64** [comment]
+1 Axum is far superior and it's no fault of the Cloudflare workers devs. There simply aren't enough resources to make it compete.

This repo does feature a `worker-sys` crate, so maybe someone can make 3rd party compatibility crates for Axum/Actix/Rocket.

**Comment by spigaz** [comment]
Well someone already did an adapter for axum:
https://logankeenan.com/posts/rust-axum-and-cloudflare-workers/

**Comment by kflansburg** [comment]
Fixed in #477
