### ISSUE TITLE
Cannot use `wasm-bindgen` package newer than 0.2.76

### ISSUE THREAD

**Issue by cr0sh** [cloudflare/workers-rs#40]
https://github.com/cloudflare/workers-rs/blob/4da00658d68294ce0853c00898783ab131f1e2e8/worker-macros/Cargo.toml#L20 requires exact `wasm-bindgen` version 0.2.76, refusing build with newer v0.2.77 dependency. Is it intended for compatibility or convenience? It seems like this 'version pinning' has been used since the first addition.

**Comment by nilslice** [comment]
Thanks, @cr0sh. At first this was for compatibility across the various crates both internal and external to this project. However, I will try to loosen this requirement and see if it is happy.

**Comment by cr0sh** [comment]
Thanks for your kind reply! Glad to hear that.
