### ISSUE TITLE
RequestInit::new() is hanging

### ISSUE THREAD

**Issue by OlegWasHere** [cloudflare/workers-rs#41]
Hi!

It seems like something's wrong with RequestInit::new(). Here is the simple code, it creates empty RequestInit and then returns empty response. And it stucks.

```
use worker::*;

mod utils;

fn log_request(req: &Request) {
    console_log!(
        "{} - [{}], located at: {:?}, within: {}",
        Date::now().to_string(),
        req.path(),
        req.cf().coordinates().unwrap_or_default(),
        req.cf().region().unwrap_or("unknown region".into())
    );
}

#[event(fetch)]
pub async fn main(req: Request, env: Env) -> Result<Response> {
    log_request(&req);

    utils::set_panic_hook();

    let _init = RequestInit::new(); // the code stucks here

    Response::empty()
}
```

And here's the logs from `wrangler dev`:

```
👂  Listening on http://127.0.0.1:8787
Sun Sep 12 2021 12:06:47 GMT+0000 (Coordinated Universal Time) - [/], located at: (59.8983, 30.2618), within: St.-Petersburg
Error: Worker exceeded CPU time limit. at line 0, col -2
{
  "exceptionDetails": {
    "columnNumber": -2,
    "exception": {
      "className": "Error",
      "description": "Error: Worker exceeded CPU time limit.",
      "preview": {
        "description": "Error: Worker exceeded CPU time limit.",
        "entries": null,
        "overflow": false,
        "properties": [],
        "subtype": "error",
        "type": "object"
      },
      "subtype": "error",
      "type": "object",
      "value": null
    },
    "lineNumber": 0,
    "text": "Uncaught (in response)",
    "url": "undefined"
  },
  "timestamp": 1631448407649
}
[2021-09-12 15:06:46] GET response-bot-dev.idebugger.workers.dev/ HTTP/1.1 503 Service Unavailable
```

**Comment by nilslice** [comment]
Thank you for reporting this. `RequestInit` definitely needs some work, but it is interesting that it seems to be consuming so much CPU. Maybe it is recursively calling something. I will take a look.

**Comment by extraymond** [comment]
> Thank you for reporting this. `RequestInit` definitely needs some work, but it is interesting that it seems to be consuming so much CPU. Maybe it is recursively calling something. I will take a look.

It's this line:
https://github.com/cloudflare/workers-rs/blob/00ce8ce9ae0d899d0d5dbc7e037a6ecd94b23c1f/worker/src/request_init.rs#L84-L88

Request_init::default called Request_init::new which called Request_init::default recursively.

**Comment by OlegWasHere** [comment]
I hope this will be fixed soon. AFAIK it's impossible to make POST requests without `RequestInit`. Is it so?

**Comment by nilslice** [comment]
@OlegWasHere - I'm aiming to get a release out today which fixes this. However, if you don't need any Cloudflare-specific features for your outbound Request, then I'd try to use another HTTP client crate that works with wasm32 target, such as [`reqwest`](https://crates.io/crates/reqwest)

**Comment by OlegWasHere** [comment]
@nilslice Oh, thanks for clarifying! I didn't know that it's possible to use other HTTP clients. And thanks for the fix :)
