### ISSUE TITLE
[BUG] Key/value 503 when requeuing message

### ISSUE THREAD

**Issue by JorritSalverda** [cloudflare/workers-rs#414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of `workers-rs` are you using?

0.0.18

### What version of `wrangler` are you using?

3.16.0

### Describe the bug

I have a queue consumer that sends a message similar to the handled one on the same queue before the 30 second timeout occurs so it can pick up where the current run left off. Unfortunately this often leads to the following failure:

```
KV GET failed: 503 Service Temporarily Unavailable
```

I've added an extra 'requeue' queue separate from the initial queue to confirm that it's only 'requeued' events that have this issue and that's indeed the case.

Does this have anything to do with how a queue message is routed to a specific instance depending on it's origin? Retries with exponential backoffs don't help out either, so it seems rather that the instance it runs on has an issue than it's a rate limiting issue.

I see it in many of our applications, where we use a similar pattern of requeuing events before execution times out. I'm under the impression that this wasn't always the case, but then again my observability was lacking in the past and we've scaled up the message rates in the meantime as well. Any thoughts?

### Steps To Reproduce

1. Create a worker that produces a message and sends it to queue A
2. Have the same worker act as a consumer and pick up the message from queue A, do something with key/value and then send the processed message onwards to queue B
3. Have the same worker now also consume messages from queue B and see it fail on KV access.

**Comment by rts-rob** [comment]
Hi @JorritSalverda - thanks for reporting. 

It's surprising to me to see a KV error. Are you also reading to/writing from a KV namespace in the same queue consumer?

For now I'll try to repro this on my side.

**Comment by JorritSalverda** [comment]
Hi @rts-rob I do write to KV indeed, but not the same key. It already fails on the first read. Might be hard to repro, but happy to jump on a call if it helps at any point.

**Comment by rts-rob** [comment]
@JorritSalverda I attempted to repro in this repository but could not with either version 0.15 or 0.18. Can you take a quick look and see if I missed something?

https://github.com/rts-rob/workers-rs-issue-414

**Comment by JorritSalverda** [comment]
@rts-rob I see you send a message to queue B, but in my case things don't start failing until I consume from the queue B and interact with the key/value store.

Essentially the following happens within a single application:

```
cron trigger -> produce event -> queue A -> consume, interact with KV and requeue -> queue B -> consume and interact with KV
```

In the first consumer all goes fine, it isn't until the last consume action that KV actions start to return the 503. I first thought it might have to do with the volume of messages and rate limiting from KV's side, but then again it only happens in that last step, not in the first consumer.

Initially I only used one queue and requeued to itself, but then I couldn't distinguish whether the KV errors happened for all events or just for requeued ones. It's not exactly the same message I requeue, just the payload.

**Comment by rts-rob** [comment]
Aha - This is not an issue with workers-rs. You're running into a known issue with the Queues service itself. 

In cases like this the combined "journey" of that request exceeds the subrequest limit. That's why it's erroring out down around the 10th subrequest.

We have a ticket open to track this internally but unfortunately cannot give you an ETA. I'll get the bug label added to this issue and leave it open until it's fixed. If you want to discuss further please ping me in the #queues-beta channel in our Discord server.

**Comment by JorritSalverda** [comment]
@rts-rob thanks for investigating and confirming that it's indeed a current limitation of queues. I'll look for a workaround - like counting the number of subrequests and stop requeuing in time - until the internal issue and limitation has been addressed.

**Comment by rts-rob** [comment]
Hi @JorritSalverda - we just rolled out a fix for this. Any chance you can try the previous behaviour and confirm whether it now works as expected?

**Comment by JorritSalverda** [comment]
Hi @rts-rob I can now easily requeue events more than 20 times, so indeed seems to fixed!
