### ISSUE TITLE
KV API vs KV Bindings

### ISSUE THREAD

**Issue by richshepard** [cloudflare/workers-rs#419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of `workers-rs` are you using?

0.0.15

### What version of `wrangler` are you using?

3.16.0

### Describe the bug

No so much a bug as a request for info.

I wrote an app that pushed 30 KV Params with code something like this:

```
    let domainhash = env.kv("domain_hashes");
    domainhashes.put("KEY", "VALUE") {
            Ok(builder) => match builder.execute().await {
                Ok(_value) => {}
                Err(_err) => {}
            },
            Err(err) => {}
        };
```

This takes 30 seconds to run which seems very slow. I then saw [this which suggested that this is correct if you use the API](https://community.cloudflare.com/t/workers-kv-api-is-super-slow-compared-to-bindings/233800).

But I thought you had to bindthe KV as it was all set in your your wrangler.toml. But I assume that isn't he case.

So the question is it possible to run Binding KV calls and if so, what am I missing?

### Steps To Reproduce

Try running this code:

```
    let domainhash = env.kv("domain_hashes");
    domainhashes.put("KEY", "VALUE") {
            Ok(builder) => match builder.execute().await {
                Ok(_value) => {}
                Err(_err) => {}
            },
            Err(err) => {}
        };
```

For me it takes a second to complete.

**Comment by kflansburg** [comment]
I believe that `env.kv` should use the bindings. Are you testing locally or on Workers?

**Comment by richshepard** [comment]
> I believe that `env.kv` should use the bindings. Are you testing locally or on Workers?

Running on a worker as I suspect testing locally won't work using KV, I may be wrong. My answer so far is to return all promises and wait on them all at the end which reduces the time to about 1 second as they all wait on IO more or less. But still 1 second per request is a little high for my liking.

**Comment by kflansburg** [comment]
Its possible that only 6 requests are made at a time due to request concurrency limits. I still wouldnt expect 6 5 sequential writes to take 1 second. 

@rts-rob do you know what might be going on here? 

One option might be to use the bulk write endpoint of the API. That single request may be faster than 30 requests to the binding.

**Comment by richshepard** [comment]
> Its possible that only 6 requests are made at a time due to request concurrency limits. I still wouldnt expect 5 sequential writes to take 1 second.
> 
> @rts-rob do you know what might be going on here?
> 
> One option might be to use the bulk write endpoint of the API. That single request may be faster than 30 requests to the binding.

OK np, I could manage a re-write to get that working, is the bulk write API exposed in the KvStore, I didn't see an api that looked right, there just seems to be get, put, list, delete etc, unless it's back a level in env.

BTW thanks for looking into this. I appriciate it.

**Comment by kflansburg** [comment]
I'm referring to the non-binding API https://developers.cloudflare.com/api/operations/workers-kv-namespace-write-multiple-key-value-pairs

**Comment by richshepard** [comment]
Thanks for all that. Really helpful.

Just one last question. I suspect I'll need to call the Bulk API via a fetch as there is no access (Javascript or Rust) to this API within code? Unless I missed that call in the SDK.

**Comment by rts-rob** [comment]
Via a fetch _from somewhere else_ or by using Wrangler:

> Write more than one key-value pair at a time with Wrangler or [via the API](https://developers.cloudflare.com/api/operations/workers-kv-namespace-write-multiple-key-value-pairs).
> 
> The bulk API can accept up to 10,000 KV pairs at once.
> 
> A key and a value are required for each KV pair. The entire request size must be less than 100 megabytes. As of January 2022, **Cloudflare does not support bulk writes from within a Worker**.

https://developers.cloudflare.com/kv/api/write-key-value-pairs/#write-data-in-bulk
