### ISSUE TITLE
[BUG] feature `tokio-postgres` does not exist on `worker`

### ISSUE THREAD

**Issue by Fyko** [cloudflare/workers-rs#437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of `workers-rs` are you using?

0.0.18

### What version of `wrangler` are you using?

3.23.0

### Describe the bug

When attempting to add the feature `tokio-postgres` to worker inline with the [example](https://github.com/cloudflare/workers-rs/tree/main/examples/tokio-postgres), cargo fails because the feature doesn't exist.

```
error: failed to select a version for `worker`.
    ... required by package `router-on-workers v0.1.0 (/home/chimmel/code/jsworkbench/jsbm.dev)`
versions that meet the requirements `^0.0.18` (locked to 0.0.18) are: 0.0.18

the package `router-on-workers` depends on `worker`, with features: `tokio-postgres` but `worker` does not have these features
```

Relevant #403

### Steps To Reproduce

1. Add the `tokio-postgres` feature to worker

```toml
[dependencies]
worker = { version = "0.0.18", features = ["tokio-postgres"] }
```

**Comment by kflansburg** [comment]
I believe that you will need to point Cargo to use `worker` off of `main` in this repository, as we have not released a version yet which contains the `tokio-postgres` feature.

**Comment by Fyko** [comment]
I tried that and was show a different error to do with wasm-bindgen. I think I'm missing something in the Config.toml to support the workspace layout
```toml
worker = { git = "https://github.com/cloudflare/workers-rs", ref= "main", features = ["tokio-postgres"]}
```

```rust
error: failed to select a version for `wasm-bindgen`.
    ... required by package `worker v0.0.18 (https://github.com/cloudflare/workers-rs#c57f7a6d)`
    ... which satisfies git dependency `worker` of package `router-on-workers v0.1.0 (/home/chimmel/code/jsworkbench/jsbm.dev)`
versions that meet the requirements `=0.2.87` are: 0.2.87

all possible versions conflict with previously selected packages.

  previously selected package `wasm-bindgen v0.2.86`
    ... which satisfies dependency `wasm-bindgen = "^0.2.37"` (locked to 0.2.86) of package `console_error_panic_hook v0.1.7`
    ... which satisfies dependency `console_error_panic_hook = "^0.1"` (locked to 0.1.7) of package `router-on-workers v0.1.0 (/home/chimmel/code/jsworkbench/jsbm.dev)`

failed to select a version for `wasm-bindgen` which could resolve this conflict
```

**Comment by kflansburg** [comment]
Yeah, it looks like you need to bump the `wasm-bindgen` that your workspace has already selected. We pin to a very specific version.

**Comment by Fyko** [comment]
That seemed to do it. Cheers!
```toml
worker = { git = "https://github.com/cloudflare/workers-rs", ref = "c57f7a6", features = [
	"tokio-postgres",
] }
wasm-bindgen = "=0.2.87"
```
