### ISSUE TITLE
[Feature] Upgrade `wasm-bindgen` to latest

### ISSUE THREAD

**Issue by itsezc** [cloudflare/workers-rs#439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When working in monorepos with Cargo workspaces, which consist of other crates which depend on `wasm-bindgen` it's likely they are using a later version of the crate, (0.2.90 at the time of writing). Instead of strictly forcing a version of it, perhaps allow the dependency for later versions as the API is very static with wasm-bindgen.

**Comment by ozwaldorf** [comment]
Also would like to see the version unpinned, due to monorepo conflicts

**Comment by allsey87** [comment]
I know this is spam, but I also need this and would appreciate seeing the version unpinned. @zebp what is the status of this crate? Does Cloudflare intend on continuing `workers-rs`?

**Comment by rakshith-ravi** [comment]
Is there a fork of this crate we can use instead that is actively developed?

**Comment by kflansburg** [comment]
Addressed in #450

**Comment by rakshith-ravi** [comment]
Great. Can we have a release with these updates?
