### ISSUE TITLE
[Feature] email event on the worker-rs

### ISSUE THREAD

**Issue by uksarkar** [cloudflare/workers-rs#446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm wondering if there is any way to handle the `email` routing events via `workers-rs`, I didn't find any events or structs related to `EmailMessage` into workers-rs. I'm unsure if I'm missing something or if is there any workaround for this.

**Comment by rikhuijzer** [comment]
I think this issue is a duplicate of https://github.com/cloudflare/workers-rs/issues/274.
