### ISSUE TITLE
Can't run wrker-build, assumes ~/.cargo/bin is in PATH and fails otherwise

### ISSUE THREAD

**Issue by tv42** [cloudflare/workers-rs#45]
#### Describe the bug

This is just developer friction / newbie trap.

Wrangler 1.19.2 installed by building via cargo.

#### Reproduce the bug

With the template Rust workers demo from https://blog.cloudflare.com/workers-rust-sdk/

```
$ wrangler dev 
🌀  Running cargo install -q worker-build && worker-build --release
sh: worker-build: command not found
Error: Build failed! Status Code: 127

$ PATH="$PATH:$HOME/.cargo/bin"
$ wrangler dev 
🌀  Running cargo install -q worker-build && worker-build --release
Installing wasm-pack...
```

#### Expected behavior

Ideally: 

1. Don't rely on user $PATH.
2. Don't even attempt to install things on the fly automatically. (My opinion.)

#### Environment and versions

Fill out the following information about your environment.

* operating system: Linux, NixOS 21.05
* output of `wrangler -V`: wrangler 1.19.2
* output of `node -v`: node: command not found
* content of `wrangler.toml`: unedited from template

**Comment by nilslice** [comment]
@tv42 - I transferred this issue to the `workers-rs` repo for posterity. I am going to close this for now, but please feel free to re-open, or continue the conversation. We are all-ears to suggestions!

**Comment by tv42** [comment]
I didn't use rustup to install rust, and consider having randomly named things from random projects at random versions in my $PATH both a usability, reproducability, and security problem. But I'm not going to bother trying to change your mind.
