### ISSUE TITLE
[BUG] All panics become "A hanging Promise was canceled" error

### ISSUE THREAD

**Issue by crestonbunch** [cloudflare/workers-rs#453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of `workers-rs` are you using?

0.0.18

### What version of `wrangler` are you using?

3.30.1

### Describe the bug

Here is a minimal failing worker, which can be easily reproduced on a new copy of the template:

```rust
use worker::*;

#[event(fetch)]
async fn main(req: Request, env: Env, ctx: Context) -> Result<Response> {
    panic!("test");
    Response::ok("Hello, World!")
}
```

Run `npm run dev` and hit the endpoint locally. It returns an unhelpful error:

```
[wrangler:inf] Ready on http://localhost:8787
✘ [ERROR] A hanging Promise was canceled. This happens when the worker runtime is waiting for a Promise from JavaScript to resolve, but has detected that the Promise cannot possibly ever resolve because all code and events related to the Promise's I/O context have already finished.


✘ [ERROR] Uncaught (in response) Error: The script will never generate a response.
```

As far as I can tell, this happens to all panics, which makes debugging very difficult. If this is expected, I'm surprised there isn't more information about how to handle panics. I would expect a more useful error message.

### Steps To Reproduce

1. Clone latest template (optionally upgrade to latest worker and wrangler packages)
2. Add `panic!()` to the starter code
3. Run `npm run dev`
4. Hit endpoint with curl or whatever
5. See unhelpful error

**Comment by kflansburg** [comment]
You should probably use https://github.com/rustwasm/console_error_panic_hook

I'm not sure if the panic behavior has changed over time (from an exception to the hanging Promise), but either way this crate should log the true error.

**Comment by crestonbunch** [comment]
Thanks, that does seem to work. Perhaps there is a future in which the worker runtime sets the panic hook automatically. But this is good for now.
