### ISSUE TITLE
[Feature] Contribution Guidance

### ISSUE THREAD

**Issue by Kakapio** [cloudflare/workers-rs#490]
Hello!

I am interested in contributing to workers-rs but wanted to get a run-down from someone on the team as to what features require development. I was hoping for someone more experienced to point me to a good first issue, or a part of the repository that needs more testing. I understand that a lot of the development team here is at Cloudflare, so I am missing a ton of insider knowledge. Sorry to make an issue for this, but I didn't know a better way to reach out.

Thank you!
Kakapio 😄

**Comment by kflansburg** [comment]
Hey @Kakapio, thanks for you interest. I have labeled a few issues as `good first issue`. Most of these relate to documentation or adding individual JavaScript methods to existing bindings. 

The repository is also undergoing a larger project to move from using custom HTTP types to using Rust's `http` crate. I think there may be some opportunities for parallel work-streams if you are interested.

**Comment by Kakapio** [comment]
> The repository is also undergoing a larger project to move from using custom HTTP types to using Rust's `http` crate. I think there may be some opportunities for parallel work-streams if you are interested.

Would love to hear more.

**Comment by kflansburg** [comment]
This is just sort of a general effort, not documented in a ticket, but primarily various types need to be converted to use `http` types where possible (behind crate flag `http`). They also need to be made `Send` because `axum` expects this. Here is a potential good ticket for this https://github.com/cloudflare/workers-rs/issues/492

**Comment by Kakapio** [comment]
> This is just sort of a general effort, not documented in a ticket, but primarily various types need to be converted to use `http` types where possible (behind crate flag `http`). They also need to be made `Send` because `axum` expects this. Here is a potential good ticket for this #492

Is there anywhere in particular you would like me to start looking? Replacing the custom types with http sounds fun. I'm happy to give it a go.

**Comment by kflansburg** [comment]
So the next thing I was thinking of looking into was what our guidance will be for making HTTP requests. With the old types, we have the global `fetch` API, but there are some rough edges and I think in the new model people may prefer to just use something like `reqwest` or `hyper`. 

So I was thinking the next step would be to remove the Fetcher in `global.rs` when the `http` feature is enabled, and then see how ergonomic it is to use one of those libraries in the test suite. We may end up maintaining an API similar to `fetch` that uses `reqwest` under the hood. 

One rub that I think I saw is that `reqwest` does not appear to use `http` 1.0 yet? Not sure what the status / roadmap is for this.

**Comment by avsaase** [comment]
`reqwest` 0.12, released last week, migrated to`http` 1.0. https://github.com/seanmonstar/reqwest/releases/tag/v0.12.0
