### ISSUE TITLE
[Feature] Make `chrono-tz` an optional dependency

### ISSUE THREAD

**Issue by avsaase** [cloudflare/workers-rs#519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I was looking though a compiled wasm binary using `wasm-objdump` and I noticed there is a lot of data in the data section related to time zones. In our own code we use `chrono-tz ` with the `filter-by-regex` feature to select which time zones are compiled (see [here](https://github.com/chronotope/chrono-tz?tab=readme-ov-file#limiting-the-timezone-table-to-zones-of-interest)) but this feature is not enabled in the `worker` crate. I suspect this causes the filter to not work because in the data section of my binary I see time zones that should have been filtered out.

The only place where `chrono-tz` is used is here:
https://github.com/cloudflare/workers-rs/blob/79ce476af039229f30989594b1167e8fbe058c74/worker/src/cf.rs#L153-L157

This makes me think there's an easy opportunity for some binary size saving by either 
1. adding a (potentially default) feature that enables the `chrono-tz` dependency and guards this function
2. enabling the `filter-by-regex` feature and change the return type of this function to an `Option` (maybe that's a good idea anyway?). 
3. getting rid of the function altogether is also an option.

I suppose a combination of 1 and 2 is also possible but probably overkill. 

What do you think? I'm happy to make a PR.

**Comment by spigaz** [comment]
I'm not sure how much you are saving, have you tried a simple project with it and without it?

That's the clients timezone in many use cases it might be handy, but I guess in most workers its not going to be relevant.

But I agree you have a valid point, the core should be as minimalist as possible, no queues, no r2, no d1, no kv, as much bare as possible and the rest should be enabled as features.

Even if the features enabled by default are all of them to make it easier, one should be able to disable everything that isn't required.

**Comment by avsaase** [comment]
In my worker that also directly depends on and uses code from `chrono-tz`, a filter on UTC and European time zones saves ~700kb pre-compression, ~100kb gzipped. I haven't tested what the difference is in a smaller project.

I found that making the changes in 1 and not enabling the feature didn't make any difference in binary size (the time zones I'm seeing in my binary are due to an unrelated crate). This means the filter works even though the `filter_by_regex` feature is not enabled in `worker`. This creates another problem because the current code panics when parsing fails, which will happen if the time zone is not compiled into the binary.

**Comment by spigaz** [comment]
To understand the benefits of disabling a dependency, its relevant to know how much it implies to a bare project that doesn't use it.

On the other hand, DCE already removes unused functions, and I'm not sure how hard it would be to add what's in its TODO list:
- Support DCE for exported global, memory, table.
- Remove elements only used by this function (other imports, data, etc).
https://github.com/xtuc/webassemblyjs/tree/master/packages/dce

That would yield a more general and effective solution, still I'm not sure why rustc doesn't do this by itself...

--
In your case I would start with an empty project and only add dependencies at first to check what happens, because it can be macro expansions.

If that's the case, either you can't run away from it, or an approach like DCE is the only solution you have AFAIK.

**Comment by kflansburg** [comment]
This is a great, find, thanks!

> I found that making the changes in 1 and not enabling the feature didn't make any difference in binary size (the time zones I'm seeing in my binary are due to an unrelated crate). This means the filter works even though the `filter_by_regex` feature is not enabled in `worker`. 

I'm having trouble following this. I would expect that if your Cargo workspace enabled the feature, then it's enabled and would apply the filter. These two sentences above seem to say different things in that regard. 

I will take a look at making this dependency optional though. Makes a lot of sense.

**Comment by avsaase** [comment]
That method also exists: https://github.com/cloudflare/workers-rs/blob/ee2c48783df0f63d82c565c8046fb15698c176c2/worker/src/cf.rs#L162-L165

**Comment by spigaz** [comment]
Thanks @avsaase!

Then problem solved! :)

Sorry, I should have checked!
