### ISSUE TITLE
[BUG] `http` feature is not named accurately.

### ISSUE THREAD

**Issue by fakeshadow** [cloudflare/workers-rs#531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of `workers-rs` are you using?

0.0.24

### What version of `wrangler` are you using?

2.13.0

### Describe the bug

`http` feature unconditionally depend on `axum` and I don't even use said crate. My suggestion is one of the following:
1. Rename the feature to `axum`, `axum-http` or anything to reflect that `axum` is a major extra dep imported.
2. Remove `axum` from the feature and depend solely on `http` and `http-body` for http types.

### Steps To Reproduce

adding `worker = { version = "0.0.24", features = ["http"] }` to any rust project and run `cargo tree` to see axum being imported.

**Comment by kflansburg** [comment]
I plan to split the axum dependency into a separate feature in the next release.
