### ISSUE TITLE
[BUG] `worker-kv` is not released together with other crates

### ISSUE THREAD

**Issue by avsaase** [cloudflare/workers-rs#539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of `workers-rs` are you using?

0.1.0

### What version of `wrangler` are you using?

3.47.1

### Describe the bug

The `worker-kv` crate was moved to this repo in https://github.com/cloudflare/workers-rs/pull/494 but there hasn't been a new release and the `worker` crate still depends on an older `worker-kv` version. Changes made during/after the move (most notably https://github.com/cloudflare/workers-rs/pull/494/commits/edf1680eb80e4d74666a4cf9a1d784ed5b09eaa0) are not available to users. Is this intentional?

**Comment by kflansburg** [comment]
I don't think they should be released together, as KV may not change as frequently. Unfortunately I'm still working on getting access to publish the `worker-kv` crate.

**Comment by avsaase** [comment]
No you're right it's not strictly necessary. It would be easier to keep everything in sync that way though.

**Comment by kflansburg** [comment]
@avsaase, I now have publish access and have published the new version (`0.7.0`). The old repository has been archived. 

Given the fact that KV is already on `0.7` and worker is now just on `0.1` and KV may still change at a different cadence from worker, I don't think they should be published together, but I will start thinking about tooling for automating KV releases and doing them more frequently.
