### ISSUE TITLE
Workers Sites support

### ISSUE THREAD

**Issue by SeokminHong** [cloudflare/workers-rs#54]
Hi 👋 

I had tried to re-implement the Workers Sites using Rust, but I was stuck by KV access.

As far as I know, the [kv-asset-handler](https://github.com/cloudflare/kv-asset-handler) package uses the `STATIC_CONTENT_MANIFEST` variable from global context generated by wrangler. Am I right?

If it is, can you provide some ways to accessing the manifest or Rust version of `getAssetFromKV` function?

**Comment by nilslice** [comment]
I don't have a solution in mind for this, but it is a good question.  
The team is generally recommending the use of Cloudflare Pages instead of Worker Sites, but I understand the desire to use it.

I'm not super familiar with the asset manifest, or with Workers Sites, but will start tracking this request and see if there is something we will officially support. 

For now, the code in the Wrangler codebase (https://github.com/cloudflare/wrangler) may point you in the right direction as to reading/deconstructing the asset manifest for use in a Rust KvAssetHandler.

**Comment by Dav1dde** [comment]
You can access static files through the`__STATIC_CONTENT` KV:

```rust
#[event(fetch)]
pub async fn main(req: worker::Request, env: worker::Env) -> worker::Result<worker::Response> {
    let kv = worker::kv::KvStore::from_this(&env, "__STATIC_CONTENT")?;

    let index = kv.get("index.html").text().await?.expect("index html");
    worker::Response::from_html(index)
}
```

There is still a lot missing, like caching, mime types etc, butyou can just follow the JS implementation of `getAssetFromKV` to do that yourself, e.g. I have a small helper like this:

```rust
pub async fn serve_asset(req: Request, store: KvStore) -> worker::Result<Response> {
    let path = req.path();
    let path = path.trim_start_matches('/');
    let value = match store.get(path).bytes().await? {
        Some(value) => value,
        None => return Response::error("Not Found", 404),
    };
    let mut response = Response::from_bytes(value)?;
    response
        .headers_mut()
        .set("Content-Type", get_mime(path).unwrap_or("text/plain"))?;
    Ok(response)
}

fn get_mime(path: &str) -> Option<&'static str> {
    let ext = if let Some((_, ext)) = path.rsplit_once(".") {
        ext
    } else {
        return None;
    };

    let ct = match ext {
        "html" => "text/html",
        "css" => "text/css",
        "js" => "text/javascript",
        "json" => "application/json",
        "png" => "image/png",
        "jpg" => "image/jpeg",
        "jpeg" => "image/jpeg",
        "ico" => "image/x-icon",
        "wasm" => "application/wasm",
        _ => return None,
    };

    return Some(ct);
}
```

**Comment by nilslice** [comment]
Thank you for the explanation here, @Dav1dde!

One minor note, is that you should be able to use the `kv` method on `Env` to access a KV namespace. So instead of: 

```rust
let kv = worker::kv::KvStore::from_this(&env, "__STATIC_CONTENT")?;
```
you can do: 
```rust 
let kv = env.kv("__STATIC_CONENT")?;
```

The caveat is that you're forced to use the `worker::kv::KvStore` type from the version we have pinned in `workers-rs` dependencies and you might need another version. If so, please let me know :)

**Comment by Dav1dde** [comment]
Thanks, I was looking for something like `env.kv("__STATIC_CONENT")` after moving away from the router, so I just ended up copying the implementation of the router, this is a lot nicer!

The 0.5 version of the `workers-kv` crate has lots of improvements (which the master branch has already been updated to), luckily cargo makes referencing a git revision really easy, but a new release would help here.

Improvements like:
- A nicer API (imo)
- Support for actually querying binary data (like e.g. a wasm file or images) <-- that was what I needed

**Comment by Dav1dde** [comment]
@nilslice now I am actually trying to deploy this on cloudflare with wrangler, I am running into the issue that the files are hashed and I don't seem to have access to the manifest `__STATIC_CONTENT_MANIFEST`, how do I read the manifest?

**Comment by Dav1dde** [comment]
I have a solution now, but I wish it wasn't necessary:

Have a post-processing script:
```sh
cat <<EOF > build/worker/assets.mjs
import manifestJSON from '__STATIC_CONTENT_MANIFEST'
const assetManifest = JSON.parse(manifestJSON)

export function get_asset(name) {
    return assetManifest[name];
}
EOF
```

Then you can access it in Rust:

```rust
#[wasm_bindgen(raw_module = "./assets.mjs")]
extern "C" {
    fn get_asset(name: &str) -> Option<String>;
}

pub fn resolve(name: &str) -> Cow<'_, str> {
    match get_asset(name) {
        Some(name) => Cow::Owned(name),
        None => Cow::Borrowed(name),
    }
}
```

**Comment by SeokminHong** [comment]
Thanks to @Dav1dde , I also found a solution without using JavaScript directly.

```rust
#[wasm_bindgen(module = "__STATIC_CONTENT_MANIFEST")]
extern "C" {
    #[wasm_bindgen(js_name = "default")]
    static MANIFEST: String;
}

pub fn resolve(name: &str) -> Cow<'_, str> {
    match serde_json::from_str::<HashMap<String, String>>(&MANIFEST)
        .ok()
        .and_then(|m| m.get(name).cloned())
    {
        Some(val) => Cow::Owned(val),
        None => Cow::Borrowed(name),
    }
}
```

**Comment by SeokminHong** [comment]
> Thanks to @Dav1dde , I also found a solution without using JavaScript directly.
> 
> ```rust
> #[wasm_bindgen(module = "__STATIC_CONTENT_MANIFEST")]
> extern "C" {
>     #[wasm_bindgen(js_name = "default")]
>     static MANIFEST: String;
> }
> 
> pub fn resolve(name: &str) -> Cow<'_, str> {
>     match serde_json::from_str::<HashMap<&str, &str>>(&MANIFEST)
>         .ok()
>         .and_then(|m| m.get(name).map(|v| v.to_string()))
>     {
>         Some(val) => Cow::Owned(val),
>         None => Cow::Borrowed(name),
>     }
> }
> ```

This solution wouldn't work with the latest `worker-build` because of the `swc-bundler`. SWC bundler tries to resolve `import {default as default0} from "__STATIC_CONTENT_MANIFEST"`, and it will fail during bundling.

**Comment by allsey87** [comment]
@nilslice there seem to be a couple good solutions proposed above. Would you be open to accepting a PR for either @Dav1dde or @SeokminHong solution?

**Comment by nilslice** [comment]
Hi @allsey87 - I'm not at Cloudflare anymore and don't have a good line of sight into the priorities here, nor the ability to merge anything. 

Maybe @zebp could provide some feedback though.

**Comment by SeokminHong** [comment]
@allsey87 That's right. And I also made a commit to handle the latest worker-build for my own use: https://github.com/cloudflare/workers-rs/commit/5c7051daf53e4b93667568c34ea8cafa2550f669

At that time, the cache API wasn't merged so I stopped working for the kv asset handler.

**Comment by allsey87** [comment]
@SeokminHong not really the place to ask, but what pattern did you use for matching assets in sub-directories? I am finding that
`.get_async("/:asset", |_, context| asset::serve(context))` doesn't match on `/images/some_image.png`.

**Comment by andyredhead** [comment]
You may not need the leading "/" on "/images/some_image.png" - perhaps just "images/some_image.png".

I haven't tried accessing assets in a cloudflare workers site from rust/wasm yet (was just browsing about to see if anyone else has done it already) but I have [done it from JavaScript](https://github.com/my-liminal-space/cw-site-assets/blob/main/workers-site/cw-site-assets.js), where not including the leading slash in an asset path worked ok.

**Comment by armfazh** [comment]
In #308 I propose a function that allows to make the translation of asset names,
For example: 'favicon.ico' was mangled as 'favicon.<HASH>.ico'.

**Comment by lemmih** [comment]
I'm saddened to see Sites being deprecated. Just like @allsey87, I cannot see how Pages can replace Workers.

**Comment by kflansburg** [comment]
With the introduction of Workers Assets, I'm going to close this.

**Comment by allsey87** [comment]
@kflansburg could you perhaps leave a link here to the change log, PR, or a summary of Worker Assets?

**Comment by kflansburg** [comment]
> @kflansburg could you perhaps leave a link here to the change log, PR, or a summary of Worker Assets?

This is a new platform feature, there were no changes to workers-rs. Docs: https://developers.cloudflare.com/workers/static-assets/

**Comment by BrandonDyer64** [comment]
@allsey87 They have an example on how to use it in conjunction with a full-stack leptos app: https://github.com/cloudflare/workers-rs/tree/main/templates/leptos
Even if your particular use-case isn't leptos, it might be helpful.

**Comment by BrandonDyer64** [comment]
@kflansburg In regards to this:

> there were no changes to workers-rs

What about access to [`env.ASSETS`](https://developers.cloudflare.com/workers/static-assets/binding/#binding)?

**Comment by kflansburg** [comment]
> @kflansburg In regards to this:
> 
> > there were no changes to workers-rs
> 
> What about access to [`env.ASSETS`](https://developers.cloudflare.com/workers/static-assets/binding/#binding)?

Ah, I haven't added that yet. It's only needed if you want access to static assets from your Worker, if you just want us to serve the assets without modification, that is done without invoking your Worker at all. I created https://github.com/cloudflare/workers-rs/issues/644
