### ISSUE TITLE
add GitHub Actions to make it easier for contributors and maintainers

### ISSUE THREAD

**Issue by DarthBenro008** [cloudflare/workers-rs#58]
Would suggest adding GitHub Actions (clippy and build check) which runs on every PR/merge to `main` that makes it easier for maintainers to review Pull Requests as well as for contributors to improve their coding style when they contribute to this repository.

Would be happy to raise a PR for the same :smile:

**Comment by nilslice** [comment]
Hi @DarthBenro008 -

If you would like to set up the checks, please feel free! It's definitely on our list of todos, but contributing this would be most welcome.
