### ISSUE TITLE
[Feature] Access bundled files

### ISSUE THREAD

**Issue by lemmih** [cloudflare/workers-rs#596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Is there a way to access the files bundled with a worker?

The documentation says the files can be accessed via `import` in JS, but I'm unsure how that translates to Rust.

Documentation: https://developers.cloudflare.com/workers/wrangler/bundling/

**Comment by kflansburg** [comment]
I think you would need to modify the JS shim that is used, import the assets in JavaScript and then supply them to the WebAssembly invocation.

**Comment by lemmih** [comment]
Thanks.

**Comment by spigaz** [comment]
I'm not sure what you are up to, but there are alternative ways to include the content of files inside the assembly, for instance:

- include_str! for text files
https://doc.rust-lang.org/std/macro.include_str.html

- include_bytes! for binary files
https://doc.rust-lang.org/std/macro.include_bytes.html

They end up being loaded as constants that you can reference.

**Comment by lemmih** [comment]
Yeah, I used `include_dir!` and wrote some wrapper code to serve those files.
