### ISSUE TITLE
Unprivate or move `worker::response::ResponseBody`

### ISSUE THREAD

**Issue by trbodev** [cloudflare/workers-rs#65]
At the moment you can't create custom responses without `worker::response::ResponseBody` which is in a private module.

I think the best course of action would be to move `worker::response::ResponseBody` to `worker::ResponseBody` but as I am pretty new to Rust i'll leave this up to the maintainers.

**Comment by dbw9580** [comment]
You can use the `From<EdgeResponse>` trait implemented for `Response`: https://docs.rs/worker/0.0.6/worker/struct.Response.html#impl-From%3CResponse%3E-1, and create your custom response directly with methods of the `EdgeResponse` from here: https://docs.rs/worker-sys/0.0.2/worker_sys/response/struct.Response.html.

**Comment by nilslice** [comment]
I've merged this into `main` and will include it in the upcoming release. Thanks!
