### ISSUE TITLE
[BUG] Uncaught LinkError: WebAssembly.Instance(): Import #15 "./index_bg.js"

### ISSUE THREAD

**Issue by lopld** [cloudflare/workers-rs#654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of `workers-rs` are you using?

0.4.2

### What version of `wrangler` are you using?

3.80.5

### Describe the bug

-----------------------------------------------------------------------------------------------------
Running custom build: cargo install -q worker-build && worker-build --release
╭──────────────────────────────────────────────────────────────────────────────────────────────────╮
│  [b] open a browser, [d] open devtools, [l] turn off local mode, [c] clear console, [x] to exit  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
    Finished `release` profile [optimized] target(s) in 0.17s
[INFO]: Optional fields missing from Cargo.toml: 'description', 'repository', and 'license'. These are not necessary, but recommended
[INFO]: ✨   Done in 0.57s
[INFO]: 📦   Your wasm pkg is ready to publish at C:\git\cf_workers_images\build.

The file src changed, restarting build...
Running custom build: cargo install -q worker-build && worker-build --release
[wrangler:inf] Ready on http://127.0.0.1:8787
╭──────────────────────────────────────────────────────────────────────────────────────────────────╮
│  [b] open a browser, [d] open devtools, [l] turn off local mode, [c] clear console, [x] to exit  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
    Finished `release` profile [optimized] target(s) in 0.16s
[INFO]: Optional fields missing from Cargo.toml: 'description', 'repository', and 'license'. These are not necessary, but recommended
[INFO]: ✨   Done in 0.54s
[INFO]: 📦   Your wasm pkg is ready to publish at C:\git\cf_workers_images\build.

⎔ Starting local server...
✘ [ERROR] service core:user:cf_workers_images: Uncaught LinkError: WebAssembly.Instance(): Import #15 "./index_bg.js" "__wbg_error_53abcd6a461f73d8": function import requires a callable

    at null.<anonymous> (shim.js:41:9)

✘ [ERROR] The Workers runtime failed to start. There is likely additional logging output above.

If you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose

--------------------------------------------------------------------------

What is index_bg.js??? 

### Steps To Reproduce

![스크린샷 2024-10-17 205927](https://github.com/user-attachments/assets/e6829c8b-71da-4620-aa7f-6f09ba1f529c)

**Comment by lukevalenta** [comment]
I'm also seeing this error. I can trigger it when trying to update the `worker` crate from `0.2.0` to anything higher.

**Comment by kflansburg** [comment]
Are you also running in Windows?

**Comment by lukevalenta** [comment]
Running on macOS.

**Comment by PeterMHammond** [comment]
This just started happening for my Cloudflare Build process that has been working for weeks.
This it might be connected to the latest build of wrangler.
 ⛅️ wrangler 3.81.0

`2024-10-18T20:21:01.013Z	✘ [ERROR] A request to the Cloudflare API (/accounts/e2ecc897eaa02efed7cb3cbc4beca1fa/workers/scripts/scripture/versions) failed.
2024-10-18T20:21:01.013Z	
2024-10-18T20:21:01.013Z	  Uncaught LinkError: WebAssembly.Instance(): Import #30 "./index_bg.js" "__wbg_error_53abcd6a461f73d8": function import requires a callable
2024-10-18T20:21:01.013Z	    at null.<anonymous> (file:///opt/buildhome/repo/build/worker/shim.mjs:1:4526)
2024-10-18T20:21:01.013Z	   [code: 10021]
2024-10-18T20:21:01.014Z	
2024-10-18T20:21:01.014Z	  
2024-10-18T20:21:01.014Z	  If you think this is a bug, please open an issue at: https://github.com/cloudflare/workers-sdk/issues/new/choose
2024-10-18T20:21:01.014Z	`

**Comment by PeterMHammond** [comment]
I checked my commits, and confirmed this just started happening two days ago.  I think I did upgrade my local Wrangler to latest, but I made no changes to the configuration of the project other than changing my own package version number.  Once I noticed it was failing, I've tried multiple steps to resolve and revert back without any success.  I do have similar workers, that are still building, so unsure of what's the cause.
![image](https://github.com/user-attachments/assets/70651697-ca92-4562-9b54-b3e603acf934)
![image](https://github.com/user-attachments/assets/6da7861d-35e0-4787-a521-7109094a5f73)

**Comment by PeterMHammond** [comment]
Just confirmed this other worker is now failing to build on Cloudflare as well, and the only thing I changed was the package version number to trigger a build on commit.
![image](https://github.com/user-attachments/assets/e73c9938-ec8c-4c38-b40a-61237bcb1a4e)

**Comment by dinfer** [comment]
same problem here. is `workers-rs` ready to be used for developers ?

**Comment by omarabid** [comment]
I suspect this is a problem on Cloudflare side. I am getting the same error message using a project with old Wrangler/worker versions.

**Comment by kflansburg** [comment]
So far I have been unable to reproduce this. Has anyone been able to reproduce this from a fresh project (hello world template)? If you are able to reproduce, can you share the following versions: `miniflare`, `wrangler`, `workerd` (`node_modules/@cloudflare/workerd-darwin-arm64/bin/workerd --version`). 

I suspect that this may be an issue with workerd or miniflare. @jasnell does this look like something we have touched recently?

**Comment by lukevalenta** [comment]
I think this might have to do with running on rust nightly. I just encountered the issue from the `hello-world` template (after running `cargo generate cloudflare/workers-rs`) and switching from rust nightly to stable fixed the issue for me, both in the template and in my original project.

```
% cargo generate cloudflare/workers-rs
⚠️    Favorite `cloudflare/workers-rs` not found in config, using it as a git repository: https://github.com/cloudflare/workers-rs.git
✔ 🤷   Which template should be expanded? · templates/hello-world
🤷   Project Name: debug
🔧   Destination: /Users/lvalenta/cf-repos/wrangler-debug/debug ...
🔧   project-name: debug ...
🔧   Generating template ...
🔧   Moving generated files into: `/Users/lvalenta/cf-repos/wrangler-debug/debug`...
🔧   Initializing a fresh Git repository
✨   Done! New project created /Users/lvalenta/cf-repos/wrangler-debug/debug
% cd debug
% npx wrangler dev
Need to install the following packages:
wrangler@3.81.0
Ok to proceed? (y) y
<snip>
⎔ Starting local server...
✘ [ERROR] service core:user:debug: Uncaught LinkError: WebAssembly.Instance(): Import #9 "./index_bg.js" "__wbg_error_53abcd6a461f73d8": function import requires a callable

    at null.<anonymous> (shim.js:41:9)



✘ [ERROR] The Workers runtime failed to start. There is likely additional logging output above.


If you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose
```

Then switching rust to stable, it works:

 ⛅️ wrangler 3.81.0
-------------------

% rustc --version
rustc 1.83.0-nightly (da889684c 2024-09-20)
% rustup default stable
info: using existing install for 'stable-aarch64-apple-darwin'
info: default toolchain set to 'stable-aarch64-apple-darwin'

  stable-aarch64-apple-darwin unchanged - rustc 1.81.0 (eeb90cda1 2024-09-04)

% npx wrangler dev

 ⛅️ wrangler 3.81.0
-------------------

Running custom build: cargo install -q worker-build && worker-build --release
╭──────────────────────────────────────────────────────────────────────────────────────────────────╮
│  [b] open a browser, [d] open devtools, [l] turn off local mode, [c] clear console, [x] to exit  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
<snip>
[INFO]: ✨   Done in 0.20s
[INFO]: 📦   Your wasm pkg is ready to publish at /path/to/debug/build.

⎔ Starting local server...
⎔ Shutting down local server...
```

**Comment by kflansburg** [comment]
> I think this might have to do with running on rust nightly. I just encountered the issue from the `hello-world` template (after running `cargo generate cloudflare/workers-rs`) and switching from rust nightly to stable fixed the issue for me, both in the template and in my original project.


Thanks Luke, looks like I am able to reproduce on Rust nightly.

**Comment by lopld** [comment]
The problem was resolved when using the stable version of Rust.
Thanks ALL.

**Comment by omarabid** [comment]
It's not nightly, it's Rust version 1.82. I downgraded to 1.81 and was able to deploy.

This might be a problem with wasm-bindgen: https://github.com/rustwasm/wasm-bindgen/issues/4211

**Comment by lopld** [comment]
> It's not nightly, it's Rust version 1.82. I downgraded to 1.81 and was able to deploy.
> 
> This might be a problem with wasm-bindgen: [rustwasm/wasm-bindgen#4211](https://github.com/rustwasm/wasm-bindgen/issues/4211)

**Comment by PeterMHammond** [comment]
Just in case someone wants to fix the Cloudflare build process, I changed my script to pull the specific version I'm working on locally. I assume this works by avoiding the 1.82 build.

`
Build command:curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain 1.76.0 --profile minimal && export PATH="$HOME/.cargo/bin:$PATH" && rustc --version && rustup target add wasm32-unknown-unknown && cargo install -q worker-build && worker-build --release
Deploy command:export PATH="$HOME/.cargo/bin:$PATH" && npx wrangler deploy
Root directory:/`

I hope the Cloudflare build environment will eventually handle this in a more intuitive way, perhaps with toml like GitHub or with a better prebuild image to use.
But for now this works (and adding the minimal really improved the build speed).

**Comment by lennartkloock** [comment]
Bumping this, still an issue

**Comment by lukevalenta** [comment]
This workaround seems to work on the current rust stable (1.82.0): https://github.com/webpack/webpack/issues/15566#issuecomment-2421927813. Add this to `Cargo.toml`:
```
[profile.release]
strip = true
```

The next release of `wasm-bindgen` should (I hope) also incorporate a more permanent fix: https://github.com/rustwasm/wasm-bindgen/pull/4235.
