### ISSUE TITLE
could not find `worker-build` in registry `crates-io` with version `*`

### ISSUE THREAD

**Issue by tyvdh** [cloudflare/workers-rs#66]
I'm quite new to Rust development so it's entirely possible I'm doing something obviously wrong but I've tried pulling down this example and running according to the README and am getting this error. Anything obvious I need to adjust? Is my local env not setup appropriately? 

```
% wrangler build                       
🌀  Running cargo install -q worker-build && worker-build --release
error: could not find `worker-build` in registry `crates-io` with version `*`
Error: Build failed! Status Code: 101
```

**Comment by tyvdh** [comment]
Had forgotten to run `% cargo install wrangler` oof.

**Comment by tyvdh** [comment]
Hmm. Even after running `% cargo install wrangler` I'm still getting this error.

```
% cargo install worker-build
    Updating crates.io index
error: could not find `worker-build` in registry `crates-io` with version `*`
```

**Comment by nilslice** [comment]
hmm.. which version of `cargo` are you running? `cargo --version` 

it should find the latest version on crates.io (0.0.2 at the time of this writing) and install it.

**Comment by tyvdh** [comment]
```
% cargo --version
cargo 1.55.0
```

**Comment by tyvdh** [comment]
If I run just `cargo build` I get this output
```
% cargo build       
    Updating crates.io index
error: failed to select a version for the requirement `serde_json = "^1.0.67"`
candidate versions found which didn't match: 1.0.64, 1.0.63, 1.0.62, ...
location searched: crates.io index
required by package `rust-wrangler v0.1.0`
```

**Comment by nilslice** [comment]
I've not been able to reproduce this issue. not sure where you're getting `rust-wrangler` from either, as that's nothing of ours or to do with this project.. Do you see `rust-wrangler` anywhere in your list of dependencies?

**Comment by tyvdh** [comment]
Yeah idk I'm probably out of my
league. If there are no obvious issues and no other reports let's just close and I'll stick with JS

**Comment by nilslice** [comment]
Definitely not out of your league on this! But there seems to be something wrong with your setup... if you have time to revisit, please re-open this issue and we can pick back up.
