### ISSUE TITLE
[BUG] Basic Hello World template doesn't start and fails with the attached message

### ISSUE THREAD

**Issue by saikatdas0790** [cloudflare/workers-rs#672]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of `workers-rs` are you using?

0.4.2

### What version of `wrangler` are you using?

3.90.0

### Describe the bug

Fails to start with this error message

![image](https://github.com/user-attachments/assets/8e704ff7-403a-4748-93ce-bbbe327c16b6)

Tried both stable and nightly toolchains 

Running an Ubuntu instance on Windows WSL2

### Steps To Reproduce

- Install latest Rust toolchain using rustup on Ubuntu
- cargo generate
- npx wrangler dev

**Comment by spigaz** [comment]
This is most likely a duplicate of #668, I believe you should try the workaround that is suggested... Or to try to downgrade your rust version.

**Comment by saikatdas0790** [comment]
@spigaz Thank you for the response

Tried the suggested workaround, but build still fails with this error:
![image](https://github.com/user-attachments/assets/126a16eb-a87f-43d7-b044-10a55d7fb273)

Here's a repo with the current state of things:
https://github.com/saikatdas0790/cloudflare-workers-rs-hello-world

**Comment by spigaz** [comment]
I haven't tried the workaround, but other users are downgrading to rust 1.81 for now and say that it works for them.

But I would try it by cloning the workers-rs repository, then updating its references to the git version of wasm-bindgen.

Then in my project I would update it to use the git version of wasm-bindgen and the clone I did of workers-rs that references the git version of wasm-bindgen.

**Comment by spigaz** [comment]
I don't know, there are a lot of people with the same issue, so I'm guessing that as soon as wasm-bindgen releases the next version, someone will open a PR and it will be merged, followed by a release.

If I had to guess, about two weeks.

**Comment by spigaz** [comment]
@saikatdas0790 The latest version of wasm-bindgen was just released:

https://github.com/rustwasm/wasm-bindgen/releases/tag/0.2.96

You can give it a try and report if its okay...

**Comment by saikatdas0790** [comment]
Looks like it's working now. Will play around more and come back if additional difficulties. Thanks for the help ☺️
