### ISSUE TITLE
Feature request: No matching route closure

### ISSUE THREAD

**Issue by NicholasHazen** [cloudflare/workers-rs#85]
It would be really helpful to be able to pass in a closure to the router that is run when there is no matching route. In my use case, I'd like to be able to trigger logging and analytics. I'm using the worker as a gateway and I'd like to be sure that all the requests are being handled.

**Comment by nilslice** [comment]
Sorry on mobile at the moment, but you could look at the `or_else_any_method_async` (or non-async version) on the Router, which sounds like it's what you want?

**Comment by nilslice** [comment]
@NicholasHazen - hey, just checking in to see if the suggestion above worked for you?

**Comment by NicholasHazen** [comment]
Hey, sorry for the slow response. This totally works.
