### ISSUE TITLE
Confusing error when trying to define both a durable worker and a fetch handler in the same file

### ISSUE THREAD

**Issue by eminence** [cloudflare/workers-rs#94]
Hi there,

I'm trying to play around with Durable Workers, so I copied in the `Chatroom` example from the README into my pre-existing lib.rs (which was mostly the default example after running `wrangler generate`).

My entire src/lib.rs file looks like this:

```rust
use worker::*;

#[durable_object]
pub struct Chatroom {
    state: State,
    env: Env, // access `Env` across requests, use inside `fetch`
}

#[durable_object]
impl DurableObject for Chatroom {
    fn new(state: State, env: Env) -> Self {
        Self { state: state, env }
    }

    async fn fetch(&mut self, _req: Request) -> Result<Response> {
        todo!()
    }
}

#[event(fetch)]
pub async fn main(req: Request, env: Env) -> Result<Response> {
    Response::error("Bad Request", 400)
}
```

Running `wrangler build`, I get this error:

```
[INFO]: Compiling to Wasm...
   Compiling project_name v0.1.0 (/home/achin/tmp/70/project_name)
error[E0428]: the name `__WASM_BINDGEN_GENERATED_0bdc7e4367fd39cb` is defined multiple times
  --> src/lib.rs:20:1
   |
3  | #[durable_object]
   | ----------------- previous definition of the value `__WASM_BINDGEN_GENERATED_0bdc7e4367fd39cb` here
...
20 | #[event(fetch)]
   | ^^^^^^^^^^^^^^^ `__WASM_BINDGEN_GENERATED_0bdc7e4367fd39cb` redefined here
   |
   = note: `__WASM_BINDGEN_GENERATED_0bdc7e4367fd39cb` must be defined only once in the value namespace of this module
   = note: this error originates in the attribute macro `event` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0428`.
error: could not compile `project_name` due to previous error
Error: Compiling your crate to WebAssembly failed
Caused by: failed to execute `cargo build`: exited with exit status: 101
  full command: "cargo" "build" "--lib" "--release" "--target" "wasm32-unknown-unknown"
Error: wasm-pack exited with status exit status: 1
Error: Build failed! Status Code: 1
```

I think it's illegal to define a fetch handler and also a durable object in the same file.  Is that true?
If so, I would be great if this could be detected better (better error message), and even greater if the README stated this a bit more clearly :)

## Version info:
rustc: rustc 1.58.0-nightly (dd549dcab 2021-11-25)
wrangler: wrangler 1.19.5
workers-rs: 0.0.7

**Comment by nilslice** [comment]
@eminence - thanks for reporting this! Currently, you'll need to define the Durable Object in a separate module. I will admit, this is a bit of an oversight on my part, as the naming of the generated code from the macro shouldn't collide this way. I will track this and work on a fix, but I don't think it will be ready before the end of the year with other efforts taking priority.

**Comment by eminence** [comment]
Ah, so the Durable Object and the worker handler should be in the same crate, but different modules?  I'll try that, thanks!

There's no rush on this, a fix anytime next year would be fine :)

**Comment by nilslice** [comment]
Yep! you can see an example of this layout in the `worker-sandbox` directory. However, there is currently something else broken here, which I am trying to debug.. so you may not be able to run the Durable Object yet.. If you try and hit any issues, please let me know! (also would be glad to know if it ends up working)

**Comment by eminence** [comment]
> However, there is currently something else broken here, which I am trying to debug.. so you may not be able to run the Durable Object yet.. If you try and hit any issues, please let me know!

I've been trying to copy the layout from `worker-sandbox` and I'm getting this error when running my code:

```
A hanging Promise was canceled. This happens when the worker runtime is waiting for a Promise from JavaScript to resolve, but has detected that the Promise cannot possibly ever resolve because all code and events related to the Promise's request context have already finished.
TypeError: Fetch API cannot load: /test
panicked at 'TypeError: Fetch API cannot load: /test', src/lib.rs:43:1
```

Is this perhaps the same error you are chasing?

**Comment by nilslice** [comment]
That's the one!

**Comment by nilslice** [comment]
@eminence - have you "accepted" the new pricing plan in your dashboard, now that Durable Objects are generally available / out of Beta?

If not, please do by logging in & visiting this URL `https://dash.cloudflare.com/<ACCOUNT_ID>/workers/overview?enable-durable-objects`, and try again.

**Comment by eminence** [comment]
Hi @nilslice -- Yes, I've done that.  

Here's what I see in the top-right of my dashboard when I visit the URL you suggested (which I think means I've correctly accepted the new pricing)

![image](https://user-images.githubusercontent.com/402454/144933766-91153f2a-4d09-41d7-b489-0ccfe93b70b2.png)

**Comment by nilslice** [comment]
Ok, thank you for confirming! I have been able to run the Durable Object example in the demo, as well as a few others from the community, so I don't think we're dealing with the same issue. 

If you'd like to share some more info, or bits of relevant code, that would be great -- happy to try and help debug whatever problem you're running into. Ideally I could see the `fetch` call you're making to the DO from the Worker, as well as the DO code itself.

**Comment by eminence** [comment]
I very much appreciate the offer of help.  I've created a new temp repo that contains my full code (plus Cargo.lock and wrangler.toml), plus a README that has the full transcripts of the errors:

https://github.com/eminence/test-workers-rust/tree/4fac1d5d0e3fd88dd5ef654ecd432174780f4fae

Thanks again.

**Comment by nilslice** [comment]
Hey, @eminence - can you try changing this `fetch_with_str` call: https://github.com/eminence/test-workers-rust/blob/4fac1d5d0e3fd88dd5ef654ecd432174780f4fae/src/lib.rs#L50

to instead use a full `https://some-domain/test` ? it doesn't need to be a real domain, given that the `fetch` is made directly to your DO. There may have been some subtle runtime change, where this used to work when passed only a `path` in place of a full URL.

**Comment by nilslice** [comment]
The runtime team made a change, and it slipped by, and should have been made clear by updating examples in this repo... 

The change in particular is that we modified how the runtime interprets `fetch` calls to Durable Objects, https://developers.cloudflare.com/workers/platform/changelog#10212021

`durable_object_fetch_requires_full_url` is a new compatibility flag that _could_ be added to `wrangler.toml` to opt-in to the old behavior.

**Comment by eminence** [comment]
That work, thanks!

**Comment by nilslice** [comment]
Great! I'm going to close this for now, and track internally the original issue of same-module DO's. Thanks for your patience & help debugging.
